// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package businessbankmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the BusinessBankModule module
	public static boolean sanityCheck(IContext context, businessbankmodule.proxies.PaymentOrder _paymentOrder)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PaymentOrder", _paymentOrder == null ? null : _paymentOrder.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("BusinessBankModule.SanityCheck").withParams(params).execute(context);
	}
}