// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package businessbankmodule.proxies;

public class AccountStatusReport
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject accountStatusReportMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BusinessBankModule.AccountStatusReport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		timestamp("timestamp"),
		AccountStatusReport_Account("BusinessBankModule.AccountStatusReport_Account"),
		DocumentAccountStatusReport_AccountStatusReport("BusinessBankModule.DocumentAccountStatusReport_AccountStatusReport");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AccountStatusReport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BusinessBankModule.AccountStatusReport"));
	}

	protected AccountStatusReport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject accountStatusReportMendixObject)
	{
		if (accountStatusReportMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BusinessBankModule.AccountStatusReport", accountStatusReportMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BusinessBankModule.AccountStatusReport");

		this.accountStatusReportMendixObject = accountStatusReportMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AccountStatusReport.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static businessbankmodule.proxies.AccountStatusReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return businessbankmodule.proxies.AccountStatusReport.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static businessbankmodule.proxies.AccountStatusReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new businessbankmodule.proxies.AccountStatusReport(context, mendixObject);
	}

	public static businessbankmodule.proxies.AccountStatusReport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return businessbankmodule.proxies.AccountStatusReport.initialize(context, mendixObject);
	}

	public static java.util.List<businessbankmodule.proxies.AccountStatusReport> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<businessbankmodule.proxies.AccountStatusReport> result = new java.util.ArrayList<businessbankmodule.proxies.AccountStatusReport>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//BusinessBankModule.AccountStatusReport" + xpathConstraint))
			result.add(businessbankmodule.proxies.AccountStatusReport.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of timestamp
	 */
	public final java.util.Date gettimestamp()
	{
		return gettimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of timestamp
	 */
	public final java.util.Date gettimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.timestamp.toString());
	}

	/**
	 * Set value of timestamp
	 * @param timestamp
	 */
	public final void settimestamp(java.util.Date timestamp)
	{
		settimestamp(getContext(), timestamp);
	}

	/**
	 * Set value of timestamp
	 * @param context
	 * @param timestamp
	 */
	public final void settimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timestamp)
	{
		getMendixObject().setValue(context, MemberNames.timestamp.toString(), timestamp);
	}

	/**
	 * @return value of AccountStatusReport_Account
	 */
	public final businessbankmodule.proxies.Account getAccountStatusReport_Account() throws com.mendix.core.CoreException
	{
		return getAccountStatusReport_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountStatusReport_Account
	 */
	public final businessbankmodule.proxies.Account getAccountStatusReport_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AccountStatusReport_Account.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AccountStatusReport_Account
	 * @param accountstatusreport_account
	 */
	public final void setAccountStatusReport_Account(businessbankmodule.proxies.Account accountstatusreport_account)
	{
		setAccountStatusReport_Account(getContext(), accountstatusreport_account);
	}

	/**
	 * Set value of AccountStatusReport_Account
	 * @param context
	 * @param accountstatusreport_account
	 */
	public final void setAccountStatusReport_Account(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.Account accountstatusreport_account)
	{
		if (accountstatusreport_account == null)
			getMendixObject().setValue(context, MemberNames.AccountStatusReport_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AccountStatusReport_Account.toString(), accountstatusreport_account.getMendixObject().getId());
	}

	/**
	 * @return value of DocumentAccountStatusReport_AccountStatusReport
	 */
	public final businessbankmodule.proxies.DocumentAccountStatusReport getDocumentAccountStatusReport_AccountStatusReport() throws com.mendix.core.CoreException
	{
		return getDocumentAccountStatusReport_AccountStatusReport(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentAccountStatusReport_AccountStatusReport
	 */
	public final businessbankmodule.proxies.DocumentAccountStatusReport getDocumentAccountStatusReport_AccountStatusReport(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.DocumentAccountStatusReport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocumentAccountStatusReport_AccountStatusReport.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.DocumentAccountStatusReport.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocumentAccountStatusReport_AccountStatusReport
	 * @param documentaccountstatusreport_accountstatusreport
	 */
	public final void setDocumentAccountStatusReport_AccountStatusReport(businessbankmodule.proxies.DocumentAccountStatusReport documentaccountstatusreport_accountstatusreport)
	{
		setDocumentAccountStatusReport_AccountStatusReport(getContext(), documentaccountstatusreport_accountstatusreport);
	}

	/**
	 * Set value of DocumentAccountStatusReport_AccountStatusReport
	 * @param context
	 * @param documentaccountstatusreport_accountstatusreport
	 */
	public final void setDocumentAccountStatusReport_AccountStatusReport(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.DocumentAccountStatusReport documentaccountstatusreport_accountstatusreport)
	{
		if (documentaccountstatusreport_accountstatusreport == null)
			getMendixObject().setValue(context, MemberNames.DocumentAccountStatusReport_AccountStatusReport.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocumentAccountStatusReport_AccountStatusReport.toString(), documentaccountstatusreport_accountstatusreport.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return accountStatusReportMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final businessbankmodule.proxies.AccountStatusReport that = (businessbankmodule.proxies.AccountStatusReport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BusinessBankModule.AccountStatusReport";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
