// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package businessbankmodule.proxies;

public class BankAccountsReport
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bankAccountsReportMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BusinessBankModule.BankAccountsReport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		timestamp("timestamp"),
		BankAccountsReport_Account("BusinessBankModule.BankAccountsReport_Account"),
		DocumentBankAccountsReport_BankAccountsReport("BusinessBankModule.DocumentBankAccountsReport_BankAccountsReport");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BankAccountsReport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BusinessBankModule.BankAccountsReport"));
	}

	protected BankAccountsReport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bankAccountsReportMendixObject)
	{
		if (bankAccountsReportMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BusinessBankModule.BankAccountsReport", bankAccountsReportMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BusinessBankModule.BankAccountsReport");

		this.bankAccountsReportMendixObject = bankAccountsReportMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BankAccountsReport.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static businessbankmodule.proxies.BankAccountsReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return businessbankmodule.proxies.BankAccountsReport.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static businessbankmodule.proxies.BankAccountsReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new businessbankmodule.proxies.BankAccountsReport(context, mendixObject);
	}

	public static businessbankmodule.proxies.BankAccountsReport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return businessbankmodule.proxies.BankAccountsReport.initialize(context, mendixObject);
	}

	public static java.util.List<businessbankmodule.proxies.BankAccountsReport> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<businessbankmodule.proxies.BankAccountsReport> result = new java.util.ArrayList<businessbankmodule.proxies.BankAccountsReport>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//BusinessBankModule.BankAccountsReport" + xpathConstraint))
			result.add(businessbankmodule.proxies.BankAccountsReport.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of timestamp
	 */
	public final java.util.Date gettimestamp()
	{
		return gettimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of timestamp
	 */
	public final java.util.Date gettimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.timestamp.toString());
	}

	/**
	 * Set value of timestamp
	 * @param timestamp
	 */
	public final void settimestamp(java.util.Date timestamp)
	{
		settimestamp(getContext(), timestamp);
	}

	/**
	 * Set value of timestamp
	 * @param context
	 * @param timestamp
	 */
	public final void settimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timestamp)
	{
		getMendixObject().setValue(context, MemberNames.timestamp.toString(), timestamp);
	}

	/**
	 * @return value of BankAccountsReport_Account
	 */
	public final java.util.List<businessbankmodule.proxies.Account> getBankAccountsReport_Account() throws com.mendix.core.CoreException
	{
		return getBankAccountsReport_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of BankAccountsReport_Account
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<businessbankmodule.proxies.Account> getBankAccountsReport_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<businessbankmodule.proxies.Account> result = new java.util.ArrayList<businessbankmodule.proxies.Account>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.BankAccountsReport_Account.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(businessbankmodule.proxies.Account.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of BankAccountsReport_Account
	 * @param bankaccountsreport_account
	 */
	public final void setBankAccountsReport_Account(java.util.List<businessbankmodule.proxies.Account> bankaccountsreport_account)
	{
		setBankAccountsReport_Account(getContext(), bankaccountsreport_account);
	}

	/**
	 * Set value of BankAccountsReport_Account
	 * @param context
	 * @param bankaccountsreport_account
	 */
	public final void setBankAccountsReport_Account(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<businessbankmodule.proxies.Account> bankaccountsreport_account)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (businessbankmodule.proxies.Account proxyObject : bankaccountsreport_account)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.BankAccountsReport_Account.toString(), identifiers);
	}

	/**
	 * @return value of DocumentBankAccountsReport_BankAccountsReport
	 */
	public final businessbankmodule.proxies.DocumentBankAccountsReport getDocumentBankAccountsReport_BankAccountsReport() throws com.mendix.core.CoreException
	{
		return getDocumentBankAccountsReport_BankAccountsReport(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentBankAccountsReport_BankAccountsReport
	 */
	public final businessbankmodule.proxies.DocumentBankAccountsReport getDocumentBankAccountsReport_BankAccountsReport(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.DocumentBankAccountsReport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocumentBankAccountsReport_BankAccountsReport.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.DocumentBankAccountsReport.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocumentBankAccountsReport_BankAccountsReport
	 * @param documentbankaccountsreport_bankaccountsreport
	 */
	public final void setDocumentBankAccountsReport_BankAccountsReport(businessbankmodule.proxies.DocumentBankAccountsReport documentbankaccountsreport_bankaccountsreport)
	{
		setDocumentBankAccountsReport_BankAccountsReport(getContext(), documentbankaccountsreport_bankaccountsreport);
	}

	/**
	 * Set value of DocumentBankAccountsReport_BankAccountsReport
	 * @param context
	 * @param documentbankaccountsreport_bankaccountsreport
	 */
	public final void setDocumentBankAccountsReport_BankAccountsReport(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.DocumentBankAccountsReport documentbankaccountsreport_bankaccountsreport)
	{
		if (documentbankaccountsreport_bankaccountsreport == null)
			getMendixObject().setValue(context, MemberNames.DocumentBankAccountsReport_BankAccountsReport.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocumentBankAccountsReport_BankAccountsReport.toString(), documentbankaccountsreport_bankaccountsreport.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bankAccountsReportMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final businessbankmodule.proxies.BankAccountsReport that = (businessbankmodule.proxies.BankAccountsReport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BusinessBankModule.BankAccountsReport";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
