// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package businessbankmodule.proxies;

public class Client
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject clientMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BusinessBankModule.Client";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		firstName("firstName"),
		surname("surname"),
		uid("uid"),
		address("address"),
		phone("phone"),
		email("email"),
		PIB("PIB"),
		MIB("MIB"),
		name("name"),
		clientType("clientType"),
		clientAgencyCodebook("BusinessBankModule.clientAgencyCodebook"),
		clientCity("BusinessBankModule.clientCity");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Client(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BusinessBankModule.Client"));
	}

	protected Client(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject clientMendixObject)
	{
		if (clientMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BusinessBankModule.Client", clientMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BusinessBankModule.Client");

		this.clientMendixObject = clientMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Client.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static businessbankmodule.proxies.Client initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return businessbankmodule.proxies.Client.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static businessbankmodule.proxies.Client initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new businessbankmodule.proxies.Client(context, mendixObject);
	}

	public static businessbankmodule.proxies.Client load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return businessbankmodule.proxies.Client.initialize(context, mendixObject);
	}

	public static java.util.List<businessbankmodule.proxies.Client> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<businessbankmodule.proxies.Client> result = new java.util.ArrayList<businessbankmodule.proxies.Client>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//BusinessBankModule.Client" + xpathConstraint))
			result.add(businessbankmodule.proxies.Client.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of firstName
	 */
	public final java.lang.String getfirstName()
	{
		return getfirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of firstName
	 */
	public final java.lang.String getfirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.firstName.toString());
	}

	/**
	 * Set value of firstName
	 * @param firstname
	 */
	public final void setfirstName(java.lang.String firstname)
	{
		setfirstName(getContext(), firstname);
	}

	/**
	 * Set value of firstName
	 * @param context
	 * @param firstname
	 */
	public final void setfirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.firstName.toString(), firstname);
	}

	/**
	 * @return value of surname
	 */
	public final java.lang.String getsurname()
	{
		return getsurname(getContext());
	}

	/**
	 * @param context
	 * @return value of surname
	 */
	public final java.lang.String getsurname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.surname.toString());
	}

	/**
	 * Set value of surname
	 * @param surname
	 */
	public final void setsurname(java.lang.String surname)
	{
		setsurname(getContext(), surname);
	}

	/**
	 * Set value of surname
	 * @param context
	 * @param surname
	 */
	public final void setsurname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String surname)
	{
		getMendixObject().setValue(context, MemberNames.surname.toString(), surname);
	}

	/**
	 * @return value of uid
	 */
	public final java.lang.String getuid()
	{
		return getuid(getContext());
	}

	/**
	 * @param context
	 * @return value of uid
	 */
	public final java.lang.String getuid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.uid.toString());
	}

	/**
	 * Set value of uid
	 * @param uid
	 */
	public final void setuid(java.lang.String uid)
	{
		setuid(getContext(), uid);
	}

	/**
	 * Set value of uid
	 * @param context
	 * @param uid
	 */
	public final void setuid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uid)
	{
		getMendixObject().setValue(context, MemberNames.uid.toString(), uid);
	}

	/**
	 * @return value of address
	 */
	public final java.lang.String getaddress()
	{
		return getaddress(getContext());
	}

	/**
	 * @param context
	 * @return value of address
	 */
	public final java.lang.String getaddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.address.toString());
	}

	/**
	 * Set value of address
	 * @param address
	 */
	public final void setaddress(java.lang.String address)
	{
		setaddress(getContext(), address);
	}

	/**
	 * Set value of address
	 * @param context
	 * @param address
	 */
	public final void setaddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.address.toString(), address);
	}

	/**
	 * @return value of phone
	 */
	public final java.lang.String getphone()
	{
		return getphone(getContext());
	}

	/**
	 * @param context
	 * @return value of phone
	 */
	public final java.lang.String getphone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.phone.toString());
	}

	/**
	 * Set value of phone
	 * @param phone
	 */
	public final void setphone(java.lang.String phone)
	{
		setphone(getContext(), phone);
	}

	/**
	 * Set value of phone
	 * @param context
	 * @param phone
	 */
	public final void setphone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.phone.toString(), phone);
	}

	/**
	 * @return value of email
	 */
	public final java.lang.String getemail()
	{
		return getemail(getContext());
	}

	/**
	 * @param context
	 * @return value of email
	 */
	public final java.lang.String getemail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.email.toString());
	}

	/**
	 * Set value of email
	 * @param email
	 */
	public final void setemail(java.lang.String email)
	{
		setemail(getContext(), email);
	}

	/**
	 * Set value of email
	 * @param context
	 * @param email
	 */
	public final void setemail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.email.toString(), email);
	}

	/**
	 * @return value of PIB
	 */
	public final java.lang.String getPIB()
	{
		return getPIB(getContext());
	}

	/**
	 * @param context
	 * @return value of PIB
	 */
	public final java.lang.String getPIB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PIB.toString());
	}

	/**
	 * Set value of PIB
	 * @param pib
	 */
	public final void setPIB(java.lang.String pib)
	{
		setPIB(getContext(), pib);
	}

	/**
	 * Set value of PIB
	 * @param context
	 * @param pib
	 */
	public final void setPIB(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pib)
	{
		getMendixObject().setValue(context, MemberNames.PIB.toString(), pib);
	}

	/**
	 * @return value of MIB
	 */
	public final java.lang.String getMIB()
	{
		return getMIB(getContext());
	}

	/**
	 * @param context
	 * @return value of MIB
	 */
	public final java.lang.String getMIB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MIB.toString());
	}

	/**
	 * Set value of MIB
	 * @param mib
	 */
	public final void setMIB(java.lang.String mib)
	{
		setMIB(getContext(), mib);
	}

	/**
	 * Set value of MIB
	 * @param context
	 * @param mib
	 */
	public final void setMIB(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mib)
	{
		getMendixObject().setValue(context, MemberNames.MIB.toString(), mib);
	}

	/**
	 * @return value of name
	 */
	public final java.lang.String getname()
	{
		return getname(getContext());
	}

	/**
	 * @param context
	 * @return value of name
	 */
	public final java.lang.String getname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.name.toString());
	}

	/**
	 * Set value of name
	 * @param name
	 */
	public final void setname(java.lang.String name)
	{
		setname(getContext(), name);
	}

	/**
	 * Set value of name
	 * @param context
	 * @param name
	 */
	public final void setname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.name.toString(), name);
	}

	/**
	 * Set value of clientType
	 * @param clienttype
	 */
	public final businessbankmodule.proxies.ClientType getclientType()
	{
		return getclientType(getContext());
	}

	/**
	 * @param context
	 * @return value of clientType
	 */
	public final businessbankmodule.proxies.ClientType getclientType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.clientType.toString());
		if (obj == null)
			return null;

		return businessbankmodule.proxies.ClientType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of clientType
	 * @param clienttype
	 */
	public final void setclientType(businessbankmodule.proxies.ClientType clienttype)
	{
		setclientType(getContext(), clienttype);
	}

	/**
	 * Set value of clientType
	 * @param context
	 * @param clienttype
	 */
	public final void setclientType(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.ClientType clienttype)
	{
		if (clienttype != null)
			getMendixObject().setValue(context, MemberNames.clientType.toString(), clienttype.toString());
		else
			getMendixObject().setValue(context, MemberNames.clientType.toString(), null);
	}

	/**
	 * @return value of clientAgencyCodebook
	 */
	public final businessbankmodule.proxies.AgencyCodebook getclientAgencyCodebook() throws com.mendix.core.CoreException
	{
		return getclientAgencyCodebook(getContext());
	}

	/**
	 * @param context
	 * @return value of clientAgencyCodebook
	 */
	public final businessbankmodule.proxies.AgencyCodebook getclientAgencyCodebook(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.AgencyCodebook result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.clientAgencyCodebook.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.AgencyCodebook.load(context, identifier);
		return result;
	}

	/**
	 * Set value of clientAgencyCodebook
	 * @param clientagencycodebook
	 */
	public final void setclientAgencyCodebook(businessbankmodule.proxies.AgencyCodebook clientagencycodebook)
	{
		setclientAgencyCodebook(getContext(), clientagencycodebook);
	}

	/**
	 * Set value of clientAgencyCodebook
	 * @param context
	 * @param clientagencycodebook
	 */
	public final void setclientAgencyCodebook(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.AgencyCodebook clientagencycodebook)
	{
		if (clientagencycodebook == null)
			getMendixObject().setValue(context, MemberNames.clientAgencyCodebook.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.clientAgencyCodebook.toString(), clientagencycodebook.getMendixObject().getId());
	}

	/**
	 * @return value of clientCity
	 */
	public final businessbankmodule.proxies.City getclientCity() throws com.mendix.core.CoreException
	{
		return getclientCity(getContext());
	}

	/**
	 * @param context
	 * @return value of clientCity
	 */
	public final businessbankmodule.proxies.City getclientCity(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.City result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.clientCity.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.City.load(context, identifier);
		return result;
	}

	/**
	 * Set value of clientCity
	 * @param clientcity
	 */
	public final void setclientCity(businessbankmodule.proxies.City clientcity)
	{
		setclientCity(getContext(), clientcity);
	}

	/**
	 * Set value of clientCity
	 * @param context
	 * @param clientcity
	 */
	public final void setclientCity(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.City clientcity)
	{
		if (clientcity == null)
			getMendixObject().setValue(context, MemberNames.clientCity.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.clientCity.toString(), clientcity.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return clientMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final businessbankmodule.proxies.Client that = (businessbankmodule.proxies.Client) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BusinessBankModule.Client";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
