// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package businessbankmodule.proxies;

public class DocumentBankAccountsReport extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BusinessBankModule.DocumentBankAccountsReport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		DocumentBankAccountsReport_BankAccountsReport("BusinessBankModule.DocumentBankAccountsReport_BankAccountsReport");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DocumentBankAccountsReport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BusinessBankModule.DocumentBankAccountsReport"));
	}

	protected DocumentBankAccountsReport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject documentBankAccountsReportMendixObject)
	{
		super(context, documentBankAccountsReportMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("BusinessBankModule.DocumentBankAccountsReport", documentBankAccountsReportMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BusinessBankModule.DocumentBankAccountsReport");
	}

	/**
	 * @deprecated Use 'DocumentBankAccountsReport.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static businessbankmodule.proxies.DocumentBankAccountsReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return businessbankmodule.proxies.DocumentBankAccountsReport.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static businessbankmodule.proxies.DocumentBankAccountsReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new businessbankmodule.proxies.DocumentBankAccountsReport(context, mendixObject);
	}

	public static businessbankmodule.proxies.DocumentBankAccountsReport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return businessbankmodule.proxies.DocumentBankAccountsReport.initialize(context, mendixObject);
	}

	public static java.util.List<businessbankmodule.proxies.DocumentBankAccountsReport> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<businessbankmodule.proxies.DocumentBankAccountsReport> result = new java.util.ArrayList<businessbankmodule.proxies.DocumentBankAccountsReport>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//BusinessBankModule.DocumentBankAccountsReport" + xpathConstraint))
			result.add(businessbankmodule.proxies.DocumentBankAccountsReport.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of DocumentBankAccountsReport_BankAccountsReport
	 */
	public final businessbankmodule.proxies.BankAccountsReport getDocumentBankAccountsReport_BankAccountsReport() throws com.mendix.core.CoreException
	{
		return getDocumentBankAccountsReport_BankAccountsReport(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentBankAccountsReport_BankAccountsReport
	 */
	public final businessbankmodule.proxies.BankAccountsReport getDocumentBankAccountsReport_BankAccountsReport(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.BankAccountsReport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocumentBankAccountsReport_BankAccountsReport.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.BankAccountsReport.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocumentBankAccountsReport_BankAccountsReport
	 * @param documentbankaccountsreport_bankaccountsreport
	 */
	public final void setDocumentBankAccountsReport_BankAccountsReport(businessbankmodule.proxies.BankAccountsReport documentbankaccountsreport_bankaccountsreport)
	{
		setDocumentBankAccountsReport_BankAccountsReport(getContext(), documentbankaccountsreport_bankaccountsreport);
	}

	/**
	 * Set value of DocumentBankAccountsReport_BankAccountsReport
	 * @param context
	 * @param documentbankaccountsreport_bankaccountsreport
	 */
	public final void setDocumentBankAccountsReport_BankAccountsReport(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.BankAccountsReport documentbankaccountsreport_bankaccountsreport)
	{
		if (documentbankaccountsreport_bankaccountsreport == null)
			getMendixObject().setValue(context, MemberNames.DocumentBankAccountsReport_BankAccountsReport.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocumentBankAccountsReport_BankAccountsReport.toString(), documentbankaccountsreport_bankaccountsreport.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final businessbankmodule.proxies.DocumentBankAccountsReport that = (businessbankmodule.proxies.DocumentBankAccountsReport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BusinessBankModule.DocumentBankAccountsReport";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
