// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package businessbankmodule.proxies;

public class DocumentPaymentOrder extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BusinessBankModule.DocumentPaymentOrder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		DocumentPaymentOrder_PaymentOrder("BusinessBankModule.DocumentPaymentOrder_PaymentOrder");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DocumentPaymentOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BusinessBankModule.DocumentPaymentOrder"));
	}

	protected DocumentPaymentOrder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject documentPaymentOrderMendixObject)
	{
		super(context, documentPaymentOrderMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("BusinessBankModule.DocumentPaymentOrder", documentPaymentOrderMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BusinessBankModule.DocumentPaymentOrder");
	}

	/**
	 * @deprecated Use 'DocumentPaymentOrder.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static businessbankmodule.proxies.DocumentPaymentOrder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return businessbankmodule.proxies.DocumentPaymentOrder.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static businessbankmodule.proxies.DocumentPaymentOrder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new businessbankmodule.proxies.DocumentPaymentOrder(context, mendixObject);
	}

	public static businessbankmodule.proxies.DocumentPaymentOrder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return businessbankmodule.proxies.DocumentPaymentOrder.initialize(context, mendixObject);
	}

	public static java.util.List<businessbankmodule.proxies.DocumentPaymentOrder> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<businessbankmodule.proxies.DocumentPaymentOrder> result = new java.util.ArrayList<businessbankmodule.proxies.DocumentPaymentOrder>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//BusinessBankModule.DocumentPaymentOrder" + xpathConstraint))
			result.add(businessbankmodule.proxies.DocumentPaymentOrder.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of DocumentPaymentOrder_PaymentOrder
	 */
	public final businessbankmodule.proxies.PaymentOrder getDocumentPaymentOrder_PaymentOrder() throws com.mendix.core.CoreException
	{
		return getDocumentPaymentOrder_PaymentOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentPaymentOrder_PaymentOrder
	 */
	public final businessbankmodule.proxies.PaymentOrder getDocumentPaymentOrder_PaymentOrder(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.PaymentOrder result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocumentPaymentOrder_PaymentOrder.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.PaymentOrder.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocumentPaymentOrder_PaymentOrder
	 * @param documentpaymentorder_paymentorder
	 */
	public final void setDocumentPaymentOrder_PaymentOrder(businessbankmodule.proxies.PaymentOrder documentpaymentorder_paymentorder)
	{
		setDocumentPaymentOrder_PaymentOrder(getContext(), documentpaymentorder_paymentorder);
	}

	/**
	 * Set value of DocumentPaymentOrder_PaymentOrder
	 * @param context
	 * @param documentpaymentorder_paymentorder
	 */
	public final void setDocumentPaymentOrder_PaymentOrder(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.PaymentOrder documentpaymentorder_paymentorder)
	{
		if (documentpaymentorder_paymentorder == null)
			getMendixObject().setValue(context, MemberNames.DocumentPaymentOrder_PaymentOrder.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocumentPaymentOrder_PaymentOrder.toString(), documentpaymentorder_paymentorder.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final businessbankmodule.proxies.DocumentPaymentOrder that = (businessbankmodule.proxies.DocumentPaymentOrder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BusinessBankModule.DocumentPaymentOrder";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
