// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package businessbankmodule.proxies;

public class PaymentOrder
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject paymentOrderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BusinessBankModule.PaymentOrder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		debtorName("debtorName"),
		creditorName("creditorName"),
		amount("amount"),
		debtorAccount("debtorAccount"),
		creditorAccount("creditorAccount"),
		urgent("urgent"),
		curencyDate("curencyDate"),
		debtorModel("debtorModel"),
		creditorModel("creditorModel"),
		debtorPurposeNumber("debtorPurposeNumber"),
		creditorPurposeNumber("creditorPurposeNumber"),
		paymentCode("paymentCode"),
		receiptDate("receiptDate"),
		paymentOrderType("paymentOrderType"),
		handled("handled"),
		purpose("purpose"),
		done("done"),
		DocumentPaymentOrder_PaymentOrder("BusinessBankModule.DocumentPaymentOrder_PaymentOrder");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PaymentOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BusinessBankModule.PaymentOrder"));
	}

	protected PaymentOrder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject paymentOrderMendixObject)
	{
		if (paymentOrderMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BusinessBankModule.PaymentOrder", paymentOrderMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BusinessBankModule.PaymentOrder");

		this.paymentOrderMendixObject = paymentOrderMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PaymentOrder.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static businessbankmodule.proxies.PaymentOrder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return businessbankmodule.proxies.PaymentOrder.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static businessbankmodule.proxies.PaymentOrder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new businessbankmodule.proxies.PaymentOrder(context, mendixObject);
	}

	public static businessbankmodule.proxies.PaymentOrder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return businessbankmodule.proxies.PaymentOrder.initialize(context, mendixObject);
	}

	public static java.util.List<businessbankmodule.proxies.PaymentOrder> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<businessbankmodule.proxies.PaymentOrder> result = new java.util.ArrayList<businessbankmodule.proxies.PaymentOrder>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//BusinessBankModule.PaymentOrder" + xpathConstraint))
			result.add(businessbankmodule.proxies.PaymentOrder.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of debtorName
	 */
	public final java.lang.String getdebtorName()
	{
		return getdebtorName(getContext());
	}

	/**
	 * @param context
	 * @return value of debtorName
	 */
	public final java.lang.String getdebtorName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.debtorName.toString());
	}

	/**
	 * Set value of debtorName
	 * @param debtorname
	 */
	public final void setdebtorName(java.lang.String debtorname)
	{
		setdebtorName(getContext(), debtorname);
	}

	/**
	 * Set value of debtorName
	 * @param context
	 * @param debtorname
	 */
	public final void setdebtorName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String debtorname)
	{
		getMendixObject().setValue(context, MemberNames.debtorName.toString(), debtorname);
	}

	/**
	 * @return value of creditorName
	 */
	public final java.lang.String getcreditorName()
	{
		return getcreditorName(getContext());
	}

	/**
	 * @param context
	 * @return value of creditorName
	 */
	public final java.lang.String getcreditorName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.creditorName.toString());
	}

	/**
	 * Set value of creditorName
	 * @param creditorname
	 */
	public final void setcreditorName(java.lang.String creditorname)
	{
		setcreditorName(getContext(), creditorname);
	}

	/**
	 * Set value of creditorName
	 * @param context
	 * @param creditorname
	 */
	public final void setcreditorName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String creditorname)
	{
		getMendixObject().setValue(context, MemberNames.creditorName.toString(), creditorname);
	}

	/**
	 * @return value of amount
	 */
	public final java.math.BigDecimal getamount()
	{
		return getamount(getContext());
	}

	/**
	 * @param context
	 * @return value of amount
	 */
	public final java.math.BigDecimal getamount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.amount.toString());
	}

	/**
	 * Set value of amount
	 * @param amount
	 */
	public final void setamount(java.math.BigDecimal amount)
	{
		setamount(getContext(), amount);
	}

	/**
	 * Set value of amount
	 * @param context
	 * @param amount
	 */
	public final void setamount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amount)
	{
		getMendixObject().setValue(context, MemberNames.amount.toString(), amount);
	}

	/**
	 * @return value of debtorAccount
	 */
	public final java.lang.String getdebtorAccount()
	{
		return getdebtorAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of debtorAccount
	 */
	public final java.lang.String getdebtorAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.debtorAccount.toString());
	}

	/**
	 * Set value of debtorAccount
	 * @param debtoraccount
	 */
	public final void setdebtorAccount(java.lang.String debtoraccount)
	{
		setdebtorAccount(getContext(), debtoraccount);
	}

	/**
	 * Set value of debtorAccount
	 * @param context
	 * @param debtoraccount
	 */
	public final void setdebtorAccount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String debtoraccount)
	{
		getMendixObject().setValue(context, MemberNames.debtorAccount.toString(), debtoraccount);
	}

	/**
	 * @return value of creditorAccount
	 */
	public final java.lang.String getcreditorAccount()
	{
		return getcreditorAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of creditorAccount
	 */
	public final java.lang.String getcreditorAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.creditorAccount.toString());
	}

	/**
	 * Set value of creditorAccount
	 * @param creditoraccount
	 */
	public final void setcreditorAccount(java.lang.String creditoraccount)
	{
		setcreditorAccount(getContext(), creditoraccount);
	}

	/**
	 * Set value of creditorAccount
	 * @param context
	 * @param creditoraccount
	 */
	public final void setcreditorAccount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String creditoraccount)
	{
		getMendixObject().setValue(context, MemberNames.creditorAccount.toString(), creditoraccount);
	}

	/**
	 * @return value of urgent
	 */
	public final java.lang.Boolean geturgent()
	{
		return geturgent(getContext());
	}

	/**
	 * @param context
	 * @return value of urgent
	 */
	public final java.lang.Boolean geturgent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.urgent.toString());
	}

	/**
	 * Set value of urgent
	 * @param urgent
	 */
	public final void seturgent(java.lang.Boolean urgent)
	{
		seturgent(getContext(), urgent);
	}

	/**
	 * Set value of urgent
	 * @param context
	 * @param urgent
	 */
	public final void seturgent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean urgent)
	{
		getMendixObject().setValue(context, MemberNames.urgent.toString(), urgent);
	}

	/**
	 * @return value of curencyDate
	 */
	public final java.util.Date getcurencyDate()
	{
		return getcurencyDate(getContext());
	}

	/**
	 * @param context
	 * @return value of curencyDate
	 */
	public final java.util.Date getcurencyDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.curencyDate.toString());
	}

	/**
	 * Set value of curencyDate
	 * @param curencydate
	 */
	public final void setcurencyDate(java.util.Date curencydate)
	{
		setcurencyDate(getContext(), curencydate);
	}

	/**
	 * Set value of curencyDate
	 * @param context
	 * @param curencydate
	 */
	public final void setcurencyDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date curencydate)
	{
		getMendixObject().setValue(context, MemberNames.curencyDate.toString(), curencydate);
	}

	/**
	 * @return value of debtorModel
	 */
	public final java.lang.String getdebtorModel()
	{
		return getdebtorModel(getContext());
	}

	/**
	 * @param context
	 * @return value of debtorModel
	 */
	public final java.lang.String getdebtorModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.debtorModel.toString());
	}

	/**
	 * Set value of debtorModel
	 * @param debtormodel
	 */
	public final void setdebtorModel(java.lang.String debtormodel)
	{
		setdebtorModel(getContext(), debtormodel);
	}

	/**
	 * Set value of debtorModel
	 * @param context
	 * @param debtormodel
	 */
	public final void setdebtorModel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String debtormodel)
	{
		getMendixObject().setValue(context, MemberNames.debtorModel.toString(), debtormodel);
	}

	/**
	 * @return value of creditorModel
	 */
	public final java.lang.String getcreditorModel()
	{
		return getcreditorModel(getContext());
	}

	/**
	 * @param context
	 * @return value of creditorModel
	 */
	public final java.lang.String getcreditorModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.creditorModel.toString());
	}

	/**
	 * Set value of creditorModel
	 * @param creditormodel
	 */
	public final void setcreditorModel(java.lang.String creditormodel)
	{
		setcreditorModel(getContext(), creditormodel);
	}

	/**
	 * Set value of creditorModel
	 * @param context
	 * @param creditormodel
	 */
	public final void setcreditorModel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String creditormodel)
	{
		getMendixObject().setValue(context, MemberNames.creditorModel.toString(), creditormodel);
	}

	/**
	 * @return value of debtorPurposeNumber
	 */
	public final java.lang.String getdebtorPurposeNumber()
	{
		return getdebtorPurposeNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of debtorPurposeNumber
	 */
	public final java.lang.String getdebtorPurposeNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.debtorPurposeNumber.toString());
	}

	/**
	 * Set value of debtorPurposeNumber
	 * @param debtorpurposenumber
	 */
	public final void setdebtorPurposeNumber(java.lang.String debtorpurposenumber)
	{
		setdebtorPurposeNumber(getContext(), debtorpurposenumber);
	}

	/**
	 * Set value of debtorPurposeNumber
	 * @param context
	 * @param debtorpurposenumber
	 */
	public final void setdebtorPurposeNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String debtorpurposenumber)
	{
		getMendixObject().setValue(context, MemberNames.debtorPurposeNumber.toString(), debtorpurposenumber);
	}

	/**
	 * @return value of creditorPurposeNumber
	 */
	public final java.lang.String getcreditorPurposeNumber()
	{
		return getcreditorPurposeNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of creditorPurposeNumber
	 */
	public final java.lang.String getcreditorPurposeNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.creditorPurposeNumber.toString());
	}

	/**
	 * Set value of creditorPurposeNumber
	 * @param creditorpurposenumber
	 */
	public final void setcreditorPurposeNumber(java.lang.String creditorpurposenumber)
	{
		setcreditorPurposeNumber(getContext(), creditorpurposenumber);
	}

	/**
	 * Set value of creditorPurposeNumber
	 * @param context
	 * @param creditorpurposenumber
	 */
	public final void setcreditorPurposeNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String creditorpurposenumber)
	{
		getMendixObject().setValue(context, MemberNames.creditorPurposeNumber.toString(), creditorpurposenumber);
	}

	/**
	 * @return value of paymentCode
	 */
	public final java.lang.String getpaymentCode()
	{
		return getpaymentCode(getContext());
	}

	/**
	 * @param context
	 * @return value of paymentCode
	 */
	public final java.lang.String getpaymentCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.paymentCode.toString());
	}

	/**
	 * Set value of paymentCode
	 * @param paymentcode
	 */
	public final void setpaymentCode(java.lang.String paymentcode)
	{
		setpaymentCode(getContext(), paymentcode);
	}

	/**
	 * Set value of paymentCode
	 * @param context
	 * @param paymentcode
	 */
	public final void setpaymentCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String paymentcode)
	{
		getMendixObject().setValue(context, MemberNames.paymentCode.toString(), paymentcode);
	}

	/**
	 * @return value of receiptDate
	 */
	public final java.util.Date getreceiptDate()
	{
		return getreceiptDate(getContext());
	}

	/**
	 * @param context
	 * @return value of receiptDate
	 */
	public final java.util.Date getreceiptDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.receiptDate.toString());
	}

	/**
	 * Set value of receiptDate
	 * @param receiptdate
	 */
	public final void setreceiptDate(java.util.Date receiptdate)
	{
		setreceiptDate(getContext(), receiptdate);
	}

	/**
	 * Set value of receiptDate
	 * @param context
	 * @param receiptdate
	 */
	public final void setreceiptDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date receiptdate)
	{
		getMendixObject().setValue(context, MemberNames.receiptDate.toString(), receiptdate);
	}

	/**
	 * Set value of paymentOrderType
	 * @param paymentordertype
	 */
	public final businessbankmodule.proxies.PaymentOrderType getpaymentOrderType()
	{
		return getpaymentOrderType(getContext());
	}

	/**
	 * @param context
	 * @return value of paymentOrderType
	 */
	public final businessbankmodule.proxies.PaymentOrderType getpaymentOrderType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.paymentOrderType.toString());
		if (obj == null)
			return null;

		return businessbankmodule.proxies.PaymentOrderType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of paymentOrderType
	 * @param paymentordertype
	 */
	public final void setpaymentOrderType(businessbankmodule.proxies.PaymentOrderType paymentordertype)
	{
		setpaymentOrderType(getContext(), paymentordertype);
	}

	/**
	 * Set value of paymentOrderType
	 * @param context
	 * @param paymentordertype
	 */
	public final void setpaymentOrderType(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.PaymentOrderType paymentordertype)
	{
		if (paymentordertype != null)
			getMendixObject().setValue(context, MemberNames.paymentOrderType.toString(), paymentordertype.toString());
		else
			getMendixObject().setValue(context, MemberNames.paymentOrderType.toString(), null);
	}

	/**
	 * @return value of handled
	 */
	public final java.lang.Boolean gethandled()
	{
		return gethandled(getContext());
	}

	/**
	 * @param context
	 * @return value of handled
	 */
	public final java.lang.Boolean gethandled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.handled.toString());
	}

	/**
	 * Set value of handled
	 * @param handled
	 */
	public final void sethandled(java.lang.Boolean handled)
	{
		sethandled(getContext(), handled);
	}

	/**
	 * Set value of handled
	 * @param context
	 * @param handled
	 */
	public final void sethandled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean handled)
	{
		getMendixObject().setValue(context, MemberNames.handled.toString(), handled);
	}

	/**
	 * @return value of purpose
	 */
	public final java.lang.String getpurpose()
	{
		return getpurpose(getContext());
	}

	/**
	 * @param context
	 * @return value of purpose
	 */
	public final java.lang.String getpurpose(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.purpose.toString());
	}

	/**
	 * Set value of purpose
	 * @param purpose
	 */
	public final void setpurpose(java.lang.String purpose)
	{
		setpurpose(getContext(), purpose);
	}

	/**
	 * Set value of purpose
	 * @param context
	 * @param purpose
	 */
	public final void setpurpose(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String purpose)
	{
		getMendixObject().setValue(context, MemberNames.purpose.toString(), purpose);
	}

	/**
	 * @return value of done
	 */
	public final java.lang.Boolean getdone()
	{
		return getdone(getContext());
	}

	/**
	 * @param context
	 * @return value of done
	 */
	public final java.lang.Boolean getdone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.done.toString());
	}

	/**
	 * Set value of done
	 * @param done
	 */
	public final void setdone(java.lang.Boolean done)
	{
		setdone(getContext(), done);
	}

	/**
	 * Set value of done
	 * @param context
	 * @param done
	 */
	public final void setdone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean done)
	{
		getMendixObject().setValue(context, MemberNames.done.toString(), done);
	}

	/**
	 * @return value of DocumentPaymentOrder_PaymentOrder
	 */
	public final businessbankmodule.proxies.DocumentPaymentOrder getDocumentPaymentOrder_PaymentOrder() throws com.mendix.core.CoreException
	{
		return getDocumentPaymentOrder_PaymentOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentPaymentOrder_PaymentOrder
	 */
	public final businessbankmodule.proxies.DocumentPaymentOrder getDocumentPaymentOrder_PaymentOrder(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.DocumentPaymentOrder result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocumentPaymentOrder_PaymentOrder.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.DocumentPaymentOrder.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocumentPaymentOrder_PaymentOrder
	 * @param documentpaymentorder_paymentorder
	 */
	public final void setDocumentPaymentOrder_PaymentOrder(businessbankmodule.proxies.DocumentPaymentOrder documentpaymentorder_paymentorder)
	{
		setDocumentPaymentOrder_PaymentOrder(getContext(), documentpaymentorder_paymentorder);
	}

	/**
	 * Set value of DocumentPaymentOrder_PaymentOrder
	 * @param context
	 * @param documentpaymentorder_paymentorder
	 */
	public final void setDocumentPaymentOrder_PaymentOrder(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.DocumentPaymentOrder documentpaymentorder_paymentorder)
	{
		if (documentpaymentorder_paymentorder == null)
			getMendixObject().setValue(context, MemberNames.DocumentPaymentOrder_PaymentOrder.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocumentPaymentOrder_PaymentOrder.toString(), documentpaymentorder_paymentorder.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return paymentOrderMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final businessbankmodule.proxies.PaymentOrder that = (businessbankmodule.proxies.PaymentOrder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BusinessBankModule.PaymentOrder";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
