// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package centralbankmodule.proxies;

public class AccountsStateByDayReport
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject accountsStateByDayReportMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CentralBankModule.AccountsStateByDayReport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		timestamp("timestamp"),
		date("date"),
		AccountsStateByDayReport_BankDailyBalance("CentralBankModule.AccountsStateByDayReport_BankDailyBalance"),
		DocumentAccountsStateByDayReport_AccountsStateByDayReport("CentralBankModule.DocumentAccountsStateByDayReport_AccountsStateByDayReport");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AccountsStateByDayReport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CentralBankModule.AccountsStateByDayReport"));
	}

	protected AccountsStateByDayReport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject accountsStateByDayReportMendixObject)
	{
		if (accountsStateByDayReportMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CentralBankModule.AccountsStateByDayReport", accountsStateByDayReportMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CentralBankModule.AccountsStateByDayReport");

		this.accountsStateByDayReportMendixObject = accountsStateByDayReportMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AccountsStateByDayReport.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static centralbankmodule.proxies.AccountsStateByDayReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return centralbankmodule.proxies.AccountsStateByDayReport.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static centralbankmodule.proxies.AccountsStateByDayReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new centralbankmodule.proxies.AccountsStateByDayReport(context, mendixObject);
	}

	public static centralbankmodule.proxies.AccountsStateByDayReport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return centralbankmodule.proxies.AccountsStateByDayReport.initialize(context, mendixObject);
	}

	public static java.util.List<centralbankmodule.proxies.AccountsStateByDayReport> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<centralbankmodule.proxies.AccountsStateByDayReport> result = new java.util.ArrayList<centralbankmodule.proxies.AccountsStateByDayReport>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CentralBankModule.AccountsStateByDayReport" + xpathConstraint))
			result.add(centralbankmodule.proxies.AccountsStateByDayReport.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of timestamp
	 */
	public final java.util.Date gettimestamp()
	{
		return gettimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of timestamp
	 */
	public final java.util.Date gettimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.timestamp.toString());
	}

	/**
	 * Set value of timestamp
	 * @param timestamp
	 */
	public final void settimestamp(java.util.Date timestamp)
	{
		settimestamp(getContext(), timestamp);
	}

	/**
	 * Set value of timestamp
	 * @param context
	 * @param timestamp
	 */
	public final void settimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timestamp)
	{
		getMendixObject().setValue(context, MemberNames.timestamp.toString(), timestamp);
	}

	/**
	 * @return value of date
	 */
	public final java.util.Date getdate()
	{
		return getdate(getContext());
	}

	/**
	 * @param context
	 * @return value of date
	 */
	public final java.util.Date getdate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.date.toString());
	}

	/**
	 * Set value of date
	 * @param date
	 */
	public final void setdate(java.util.Date date)
	{
		setdate(getContext(), date);
	}

	/**
	 * Set value of date
	 * @param context
	 * @param date
	 */
	public final void setdate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.date.toString(), date);
	}

	/**
	 * @return value of AccountsStateByDayReport_BankDailyBalance
	 */
	public final java.util.List<centralbankmodule.proxies.BankDailyBalance> getAccountsStateByDayReport_BankDailyBalance() throws com.mendix.core.CoreException
	{
		return getAccountsStateByDayReport_BankDailyBalance(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountsStateByDayReport_BankDailyBalance
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<centralbankmodule.proxies.BankDailyBalance> getAccountsStateByDayReport_BankDailyBalance(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<centralbankmodule.proxies.BankDailyBalance> result = new java.util.ArrayList<centralbankmodule.proxies.BankDailyBalance>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.AccountsStateByDayReport_BankDailyBalance.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(centralbankmodule.proxies.BankDailyBalance.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of AccountsStateByDayReport_BankDailyBalance
	 * @param accountsstatebydayreport_bankdailybalance
	 */
	public final void setAccountsStateByDayReport_BankDailyBalance(java.util.List<centralbankmodule.proxies.BankDailyBalance> accountsstatebydayreport_bankdailybalance)
	{
		setAccountsStateByDayReport_BankDailyBalance(getContext(), accountsstatebydayreport_bankdailybalance);
	}

	/**
	 * Set value of AccountsStateByDayReport_BankDailyBalance
	 * @param context
	 * @param accountsstatebydayreport_bankdailybalance
	 */
	public final void setAccountsStateByDayReport_BankDailyBalance(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<centralbankmodule.proxies.BankDailyBalance> accountsstatebydayreport_bankdailybalance)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (centralbankmodule.proxies.BankDailyBalance proxyObject : accountsstatebydayreport_bankdailybalance)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.AccountsStateByDayReport_BankDailyBalance.toString(), identifiers);
	}

	/**
	 * @return value of DocumentAccountsStateByDayReport_AccountsStateByDayReport
	 */
	public final centralbankmodule.proxies.DocumentAccountsStateByDayReport getDocumentAccountsStateByDayReport_AccountsStateByDayReport() throws com.mendix.core.CoreException
	{
		return getDocumentAccountsStateByDayReport_AccountsStateByDayReport(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentAccountsStateByDayReport_AccountsStateByDayReport
	 */
	public final centralbankmodule.proxies.DocumentAccountsStateByDayReport getDocumentAccountsStateByDayReport_AccountsStateByDayReport(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		centralbankmodule.proxies.DocumentAccountsStateByDayReport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocumentAccountsStateByDayReport_AccountsStateByDayReport.toString());
		if (identifier != null)
			result = centralbankmodule.proxies.DocumentAccountsStateByDayReport.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocumentAccountsStateByDayReport_AccountsStateByDayReport
	 * @param documentaccountsstatebydayreport_accountsstatebydayreport
	 */
	public final void setDocumentAccountsStateByDayReport_AccountsStateByDayReport(centralbankmodule.proxies.DocumentAccountsStateByDayReport documentaccountsstatebydayreport_accountsstatebydayreport)
	{
		setDocumentAccountsStateByDayReport_AccountsStateByDayReport(getContext(), documentaccountsstatebydayreport_accountsstatebydayreport);
	}

	/**
	 * Set value of DocumentAccountsStateByDayReport_AccountsStateByDayReport
	 * @param context
	 * @param documentaccountsstatebydayreport_accountsstatebydayreport
	 */
	public final void setDocumentAccountsStateByDayReport_AccountsStateByDayReport(com.mendix.systemwideinterfaces.core.IContext context, centralbankmodule.proxies.DocumentAccountsStateByDayReport documentaccountsstatebydayreport_accountsstatebydayreport)
	{
		if (documentaccountsstatebydayreport_accountsstatebydayreport == null)
			getMendixObject().setValue(context, MemberNames.DocumentAccountsStateByDayReport_AccountsStateByDayReport.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocumentAccountsStateByDayReport_AccountsStateByDayReport.toString(), documentaccountsstatebydayreport_accountsstatebydayreport.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return accountsStateByDayReportMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final centralbankmodule.proxies.AccountsStateByDayReport that = (centralbankmodule.proxies.AccountsStateByDayReport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CentralBankModule.AccountsStateByDayReport";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
