// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package centralbankmodule.proxies;

public class BillingAccount
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject billingAccountMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CentralBankModule.BillingAccount";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		accountNumber("accountNumber"),
		amount("amount"),
		ApiEndpoint("ApiEndpoint"),
		BillingAccount_CentralBank("CentralBankModule.BillingAccount_CentralBank"),
		BillingAccount_Bank("CentralBankModule.BillingAccount_Bank");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BillingAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CentralBankModule.BillingAccount"));
	}

	protected BillingAccount(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject billingAccountMendixObject)
	{
		if (billingAccountMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CentralBankModule.BillingAccount", billingAccountMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CentralBankModule.BillingAccount");

		this.billingAccountMendixObject = billingAccountMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BillingAccount.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static centralbankmodule.proxies.BillingAccount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return centralbankmodule.proxies.BillingAccount.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static centralbankmodule.proxies.BillingAccount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new centralbankmodule.proxies.BillingAccount(context, mendixObject);
	}

	public static centralbankmodule.proxies.BillingAccount load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return centralbankmodule.proxies.BillingAccount.initialize(context, mendixObject);
	}

	public static java.util.List<centralbankmodule.proxies.BillingAccount> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<centralbankmodule.proxies.BillingAccount> result = new java.util.ArrayList<centralbankmodule.proxies.BillingAccount>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CentralBankModule.BillingAccount" + xpathConstraint))
			result.add(centralbankmodule.proxies.BillingAccount.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of accountNumber
	 */
	public final java.lang.String getaccountNumber()
	{
		return getaccountNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of accountNumber
	 */
	public final java.lang.String getaccountNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.accountNumber.toString());
	}

	/**
	 * Set value of accountNumber
	 * @param accountnumber
	 */
	public final void setaccountNumber(java.lang.String accountnumber)
	{
		setaccountNumber(getContext(), accountnumber);
	}

	/**
	 * Set value of accountNumber
	 * @param context
	 * @param accountnumber
	 */
	public final void setaccountNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accountnumber)
	{
		getMendixObject().setValue(context, MemberNames.accountNumber.toString(), accountnumber);
	}

	/**
	 * @return value of amount
	 */
	public final java.math.BigDecimal getamount()
	{
		return getamount(getContext());
	}

	/**
	 * @param context
	 * @return value of amount
	 */
	public final java.math.BigDecimal getamount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.amount.toString());
	}

	/**
	 * Set value of amount
	 * @param amount
	 */
	public final void setamount(java.math.BigDecimal amount)
	{
		setamount(getContext(), amount);
	}

	/**
	 * Set value of amount
	 * @param context
	 * @param amount
	 */
	public final void setamount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amount)
	{
		getMendixObject().setValue(context, MemberNames.amount.toString(), amount);
	}

	/**
	 * @return value of ApiEndpoint
	 */
	public final java.lang.String getApiEndpoint()
	{
		return getApiEndpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of ApiEndpoint
	 */
	public final java.lang.String getApiEndpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApiEndpoint.toString());
	}

	/**
	 * Set value of ApiEndpoint
	 * @param apiendpoint
	 */
	public final void setApiEndpoint(java.lang.String apiendpoint)
	{
		setApiEndpoint(getContext(), apiendpoint);
	}

	/**
	 * Set value of ApiEndpoint
	 * @param context
	 * @param apiendpoint
	 */
	public final void setApiEndpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String apiendpoint)
	{
		getMendixObject().setValue(context, MemberNames.ApiEndpoint.toString(), apiendpoint);
	}

	/**
	 * @return value of BillingAccount_CentralBank
	 */
	public final centralbankmodule.proxies.CentralBank getBillingAccount_CentralBank() throws com.mendix.core.CoreException
	{
		return getBillingAccount_CentralBank(getContext());
	}

	/**
	 * @param context
	 * @return value of BillingAccount_CentralBank
	 */
	public final centralbankmodule.proxies.CentralBank getBillingAccount_CentralBank(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		centralbankmodule.proxies.CentralBank result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BillingAccount_CentralBank.toString());
		if (identifier != null)
			result = centralbankmodule.proxies.CentralBank.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BillingAccount_CentralBank
	 * @param billingaccount_centralbank
	 */
	public final void setBillingAccount_CentralBank(centralbankmodule.proxies.CentralBank billingaccount_centralbank)
	{
		setBillingAccount_CentralBank(getContext(), billingaccount_centralbank);
	}

	/**
	 * Set value of BillingAccount_CentralBank
	 * @param context
	 * @param billingaccount_centralbank
	 */
	public final void setBillingAccount_CentralBank(com.mendix.systemwideinterfaces.core.IContext context, centralbankmodule.proxies.CentralBank billingaccount_centralbank)
	{
		if (billingaccount_centralbank == null)
			getMendixObject().setValue(context, MemberNames.BillingAccount_CentralBank.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BillingAccount_CentralBank.toString(), billingaccount_centralbank.getMendixObject().getId());
	}

	/**
	 * @return value of BillingAccount_Bank
	 */
	public final businessbankmodule.proxies.Bank getBillingAccount_Bank() throws com.mendix.core.CoreException
	{
		return getBillingAccount_Bank(getContext());
	}

	/**
	 * @param context
	 * @return value of BillingAccount_Bank
	 */
	public final businessbankmodule.proxies.Bank getBillingAccount_Bank(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.Bank result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BillingAccount_Bank.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.Bank.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BillingAccount_Bank
	 * @param billingaccount_bank
	 */
	public final void setBillingAccount_Bank(businessbankmodule.proxies.Bank billingaccount_bank)
	{
		setBillingAccount_Bank(getContext(), billingaccount_bank);
	}

	/**
	 * Set value of BillingAccount_Bank
	 * @param context
	 * @param billingaccount_bank
	 */
	public final void setBillingAccount_Bank(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.Bank billingaccount_bank)
	{
		if (billingaccount_bank == null)
			getMendixObject().setValue(context, MemberNames.BillingAccount_Bank.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BillingAccount_Bank.toString(), billingaccount_bank.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return billingAccountMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final centralbankmodule.proxies.BillingAccount that = (centralbankmodule.proxies.BillingAccount) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CentralBankModule.BillingAccount";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
