// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package centralbankmodule.proxies;

public class DocumentAccountsStateByDayReport extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CentralBankModule.DocumentAccountsStateByDayReport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		DocumentAccountsStateByDayReport_AccountsStateByDayReport("CentralBankModule.DocumentAccountsStateByDayReport_AccountsStateByDayReport");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DocumentAccountsStateByDayReport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CentralBankModule.DocumentAccountsStateByDayReport"));
	}

	protected DocumentAccountsStateByDayReport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject documentAccountsStateByDayReportMendixObject)
	{
		super(context, documentAccountsStateByDayReportMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("CentralBankModule.DocumentAccountsStateByDayReport", documentAccountsStateByDayReportMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CentralBankModule.DocumentAccountsStateByDayReport");
	}

	/**
	 * @deprecated Use 'DocumentAccountsStateByDayReport.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static centralbankmodule.proxies.DocumentAccountsStateByDayReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return centralbankmodule.proxies.DocumentAccountsStateByDayReport.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static centralbankmodule.proxies.DocumentAccountsStateByDayReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new centralbankmodule.proxies.DocumentAccountsStateByDayReport(context, mendixObject);
	}

	public static centralbankmodule.proxies.DocumentAccountsStateByDayReport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return centralbankmodule.proxies.DocumentAccountsStateByDayReport.initialize(context, mendixObject);
	}

	public static java.util.List<centralbankmodule.proxies.DocumentAccountsStateByDayReport> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<centralbankmodule.proxies.DocumentAccountsStateByDayReport> result = new java.util.ArrayList<centralbankmodule.proxies.DocumentAccountsStateByDayReport>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CentralBankModule.DocumentAccountsStateByDayReport" + xpathConstraint))
			result.add(centralbankmodule.proxies.DocumentAccountsStateByDayReport.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of DocumentAccountsStateByDayReport_AccountsStateByDayReport
	 */
	public final centralbankmodule.proxies.AccountsStateByDayReport getDocumentAccountsStateByDayReport_AccountsStateByDayReport() throws com.mendix.core.CoreException
	{
		return getDocumentAccountsStateByDayReport_AccountsStateByDayReport(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentAccountsStateByDayReport_AccountsStateByDayReport
	 */
	public final centralbankmodule.proxies.AccountsStateByDayReport getDocumentAccountsStateByDayReport_AccountsStateByDayReport(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		centralbankmodule.proxies.AccountsStateByDayReport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocumentAccountsStateByDayReport_AccountsStateByDayReport.toString());
		if (identifier != null)
			result = centralbankmodule.proxies.AccountsStateByDayReport.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocumentAccountsStateByDayReport_AccountsStateByDayReport
	 * @param documentaccountsstatebydayreport_accountsstatebydayreport
	 */
	public final void setDocumentAccountsStateByDayReport_AccountsStateByDayReport(centralbankmodule.proxies.AccountsStateByDayReport documentaccountsstatebydayreport_accountsstatebydayreport)
	{
		setDocumentAccountsStateByDayReport_AccountsStateByDayReport(getContext(), documentaccountsstatebydayreport_accountsstatebydayreport);
	}

	/**
	 * Set value of DocumentAccountsStateByDayReport_AccountsStateByDayReport
	 * @param context
	 * @param documentaccountsstatebydayreport_accountsstatebydayreport
	 */
	public final void setDocumentAccountsStateByDayReport_AccountsStateByDayReport(com.mendix.systemwideinterfaces.core.IContext context, centralbankmodule.proxies.AccountsStateByDayReport documentaccountsstatebydayreport_accountsstatebydayreport)
	{
		if (documentaccountsstatebydayreport_accountsstatebydayreport == null)
			getMendixObject().setValue(context, MemberNames.DocumentAccountsStateByDayReport_AccountsStateByDayReport.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocumentAccountsStateByDayReport_AccountsStateByDayReport.toString(), documentaccountsstatebydayreport_accountsstatebydayreport.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final centralbankmodule.proxies.DocumentAccountsStateByDayReport that = (centralbankmodule.proxies.DocumentAccountsStateByDayReport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CentralBankModule.DocumentAccountsStateByDayReport";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
