// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package centralbankmodule.proxies;

public class DocumentBankBillingAccountStatusReport extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CentralBankModule.DocumentBankBillingAccountStatusReport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		DocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport("CentralBankModule.DocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DocumentBankBillingAccountStatusReport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CentralBankModule.DocumentBankBillingAccountStatusReport"));
	}

	protected DocumentBankBillingAccountStatusReport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject documentBankBillingAccountStatusReportMendixObject)
	{
		super(context, documentBankBillingAccountStatusReportMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("CentralBankModule.DocumentBankBillingAccountStatusReport", documentBankBillingAccountStatusReportMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CentralBankModule.DocumentBankBillingAccountStatusReport");
	}

	/**
	 * @deprecated Use 'DocumentBankBillingAccountStatusReport.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static centralbankmodule.proxies.DocumentBankBillingAccountStatusReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return centralbankmodule.proxies.DocumentBankBillingAccountStatusReport.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static centralbankmodule.proxies.DocumentBankBillingAccountStatusReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new centralbankmodule.proxies.DocumentBankBillingAccountStatusReport(context, mendixObject);
	}

	public static centralbankmodule.proxies.DocumentBankBillingAccountStatusReport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return centralbankmodule.proxies.DocumentBankBillingAccountStatusReport.initialize(context, mendixObject);
	}

	public static java.util.List<centralbankmodule.proxies.DocumentBankBillingAccountStatusReport> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<centralbankmodule.proxies.DocumentBankBillingAccountStatusReport> result = new java.util.ArrayList<centralbankmodule.proxies.DocumentBankBillingAccountStatusReport>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CentralBankModule.DocumentBankBillingAccountStatusReport" + xpathConstraint))
			result.add(centralbankmodule.proxies.DocumentBankBillingAccountStatusReport.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of DocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport
	 */
	public final centralbankmodule.proxies.BankBillingAccountStatusReport getDocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport() throws com.mendix.core.CoreException
	{
		return getDocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport
	 */
	public final centralbankmodule.proxies.BankBillingAccountStatusReport getDocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		centralbankmodule.proxies.BankBillingAccountStatusReport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport.toString());
		if (identifier != null)
			result = centralbankmodule.proxies.BankBillingAccountStatusReport.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport
	 * @param documentbankbillingaccountstatusreport_bankbillingaccountstatusreport
	 */
	public final void setDocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport(centralbankmodule.proxies.BankBillingAccountStatusReport documentbankbillingaccountstatusreport_bankbillingaccountstatusreport)
	{
		setDocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport(getContext(), documentbankbillingaccountstatusreport_bankbillingaccountstatusreport);
	}

	/**
	 * Set value of DocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport
	 * @param context
	 * @param documentbankbillingaccountstatusreport_bankbillingaccountstatusreport
	 */
	public final void setDocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport(com.mendix.systemwideinterfaces.core.IContext context, centralbankmodule.proxies.BankBillingAccountStatusReport documentbankbillingaccountstatusreport_bankbillingaccountstatusreport)
	{
		if (documentbankbillingaccountstatusreport_bankbillingaccountstatusreport == null)
			getMendixObject().setValue(context, MemberNames.DocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DocumentBankBillingAccountStatusReport_BankBillingAccountStatusReport.toString(), documentbankbillingaccountstatusreport_bankbillingaccountstatusreport.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final centralbankmodule.proxies.DocumentBankBillingAccountStatusReport that = (centralbankmodule.proxies.DocumentBankBillingAccountStatusReport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CentralBankModule.DocumentBankBillingAccountStatusReport";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
