// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package centralbankmodule.proxies;

public class Test
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CentralBankModule.Test";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		identificator("identificator"),
		attr1("attr1"),
		XMLDocument_Test("CentralBankModule.XMLDocument_Test");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Test(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CentralBankModule.Test"));
	}

	protected Test(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testMendixObject)
	{
		if (testMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CentralBankModule.Test", testMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CentralBankModule.Test");

		this.testMendixObject = testMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Test.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static centralbankmodule.proxies.Test initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return centralbankmodule.proxies.Test.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static centralbankmodule.proxies.Test initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new centralbankmodule.proxies.Test(context, mendixObject);
	}

	public static centralbankmodule.proxies.Test load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return centralbankmodule.proxies.Test.initialize(context, mendixObject);
	}

	public static java.util.List<centralbankmodule.proxies.Test> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<centralbankmodule.proxies.Test> result = new java.util.ArrayList<centralbankmodule.proxies.Test>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CentralBankModule.Test" + xpathConstraint))
			result.add(centralbankmodule.proxies.Test.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of identificator
	 */
	public final java.lang.Long getidentificator()
	{
		return getidentificator(getContext());
	}

	/**
	 * @param context
	 * @return value of identificator
	 */
	public final java.lang.Long getidentificator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.identificator.toString());
	}

	/**
	 * Set value of identificator
	 * @param identificator
	 */
	public final void setidentificator(java.lang.Long identificator)
	{
		setidentificator(getContext(), identificator);
	}

	/**
	 * Set value of identificator
	 * @param context
	 * @param identificator
	 */
	public final void setidentificator(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long identificator)
	{
		getMendixObject().setValue(context, MemberNames.identificator.toString(), identificator);
	}

	/**
	 * @return value of attr1
	 */
	public final java.lang.String getattr1()
	{
		return getattr1(getContext());
	}

	/**
	 * @param context
	 * @return value of attr1
	 */
	public final java.lang.String getattr1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.attr1.toString());
	}

	/**
	 * Set value of attr1
	 * @param attr1
	 */
	public final void setattr1(java.lang.String attr1)
	{
		setattr1(getContext(), attr1);
	}

	/**
	 * Set value of attr1
	 * @param context
	 * @param attr1
	 */
	public final void setattr1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attr1)
	{
		getMendixObject().setValue(context, MemberNames.attr1.toString(), attr1);
	}

	/**
	 * @return value of XMLDocument_Test
	 */
	public final java.util.List<centralbankmodule.proxies.XMLDocument> getXMLDocument_Test() throws com.mendix.core.CoreException
	{
		return getXMLDocument_Test(getContext());
	}

	/**
	 * @param context
	 * @return value of XMLDocument_Test
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<centralbankmodule.proxies.XMLDocument> getXMLDocument_Test(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<centralbankmodule.proxies.XMLDocument> result = new java.util.ArrayList<centralbankmodule.proxies.XMLDocument>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.XMLDocument_Test.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(centralbankmodule.proxies.XMLDocument.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of XMLDocument_Test
	 * @param xmldocument_test
	 */
	public final void setXMLDocument_Test(java.util.List<centralbankmodule.proxies.XMLDocument> xmldocument_test)
	{
		setXMLDocument_Test(getContext(), xmldocument_test);
	}

	/**
	 * Set value of XMLDocument_Test
	 * @param context
	 * @param xmldocument_test
	 */
	public final void setXMLDocument_Test(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<centralbankmodule.proxies.XMLDocument> xmldocument_test)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (centralbankmodule.proxies.XMLDocument proxyObject : xmldocument_test)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.XMLDocument_Test.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final centralbankmodule.proxies.Test that = (centralbankmodule.proxies.Test) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CentralBankModule.Test";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
