// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package centralbankmodule.proxies;

public class XMLDocument extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CentralBankModule.XMLDocument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		XMLDocument_Test("CentralBankModule.XMLDocument_Test");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public XMLDocument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CentralBankModule.XMLDocument"));
	}

	protected XMLDocument(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject xMLDocumentMendixObject)
	{
		super(context, xMLDocumentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("CentralBankModule.XMLDocument", xMLDocumentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CentralBankModule.XMLDocument");
	}

	/**
	 * @deprecated Use 'XMLDocument.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static centralbankmodule.proxies.XMLDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return centralbankmodule.proxies.XMLDocument.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static centralbankmodule.proxies.XMLDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new centralbankmodule.proxies.XMLDocument(context, mendixObject);
	}

	public static centralbankmodule.proxies.XMLDocument load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return centralbankmodule.proxies.XMLDocument.initialize(context, mendixObject);
	}

	public static java.util.List<centralbankmodule.proxies.XMLDocument> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<centralbankmodule.proxies.XMLDocument> result = new java.util.ArrayList<centralbankmodule.proxies.XMLDocument>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CentralBankModule.XMLDocument" + xpathConstraint))
			result.add(centralbankmodule.proxies.XMLDocument.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of XMLDocument_Test
	 */
	public final java.util.List<centralbankmodule.proxies.Test> getXMLDocument_Test() throws com.mendix.core.CoreException
	{
		return getXMLDocument_Test(getContext());
	}

	/**
	 * @param context
	 * @return value of XMLDocument_Test
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<centralbankmodule.proxies.Test> getXMLDocument_Test(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<centralbankmodule.proxies.Test> result = new java.util.ArrayList<centralbankmodule.proxies.Test>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.XMLDocument_Test.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(centralbankmodule.proxies.Test.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of XMLDocument_Test
	 * @param xmldocument_test
	 */
	public final void setXMLDocument_Test(java.util.List<centralbankmodule.proxies.Test> xmldocument_test)
	{
		setXMLDocument_Test(getContext(), xmldocument_test);
	}

	/**
	 * Set value of XMLDocument_Test
	 * @param context
	 * @param xmldocument_test
	 */
	public final void setXMLDocument_Test(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<centralbankmodule.proxies.Test> xmldocument_test)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (centralbankmodule.proxies.Test proxyObject : xmldocument_test)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.XMLDocument_Test.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final centralbankmodule.proxies.XMLDocument that = (centralbankmodule.proxies.XMLDocument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CentralBankModule.XMLDocument";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
