// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package businessbankmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the BusinessBankModule module
	public static void accountExportBalance(IContext context, businessbankmodule.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("BusinessBankModule.AccountExportBalance").withParams(params).execute(context);
	}
	public static void centralBankClearing(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("BusinessBankModule.CentralBankClearing").withParams(params).execute(context);
	}
	public static void centralBankRTGS(IContext context, businessbankmodule.proxies.PaymentOrder _paymentOrder)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PaymentOrder", _paymentOrder == null ? null : _paymentOrder.getMendixObject());
		Core.microflowCall("BusinessBankModule.CentralBankRTGS").withParams(params).execute(context);
	}
	public static void closeAccount(IContext context, businessbankmodule.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("BusinessBankModule.CloseAccount").withParams(params).execute(context);
	}
	public static void createAccount(IContext context, businessbankmodule.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("BusinessBankModule.CreateAccount").withParams(params).execute(context);
	}
	public static void createClient(IContext context, businessbankmodule.proxies.Client _client)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Client", _client == null ? null : _client.getMendixObject());
		Core.microflowCall("BusinessBankModule.CreateClient").withParams(params).execute(context);
	}
	public static void createPaymentOrder(IContext context, businessbankmodule.proxies.PaymentOrder _paymentOrder)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PaymentOrder", _paymentOrder == null ? null : _paymentOrder.getMendixObject());
		Core.microflowCall("BusinessBankModule.CreatePaymentOrder").withParams(params).execute(context);
	}
	public static void createPaymentOrderXMLImport(IContext context, businessbankmodule.proxies.DocumentPaymentOrder _documentPaymentOrder)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DocumentPaymentOrder", _documentPaymentOrder == null ? null : _documentPaymentOrder.getMendixObject());
		Core.microflowCall("BusinessBankModule.CreatePaymentOrderXMLImport").withParams(params).execute(context);
	}
	public static void downloadBankBillingAccountStatusReport(IContext context, businessbankmodule.proxies.DocumentBankBillingAccountStatusReport _documentBankBillingAccountStatusReport)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DocumentBankBillingAccountStatusReport", _documentBankBillingAccountStatusReport == null ? null : _documentBankBillingAccountStatusReport.getMendixObject());
		Core.microflowCall("BusinessBankModule.DownloadBankBillingAccountStatusReport").withParams(params).execute(context);
	}
	public static void exportPureXMLPaymentOrder(IContext context, businessbankmodule.proxies.PaymentOrder _paymentOrder)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PaymentOrder", _paymentOrder == null ? null : _paymentOrder.getMendixObject());
		Core.microflowCall("BusinessBankModule.ExportPureXMLPaymentOrder").withParams(params).execute(context);
	}
	public static businessbankmodule.proxies.AccountStatusReport generateAccountStatusReport(IContext context, businessbankmodule.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("BusinessBankModule.GenerateAccountStatusReport").withParams(params).execute(context);
		return result == null ? null : businessbankmodule.proxies.AccountStatusReport.initialize(context, result);
	}
	public static businessbankmodule.proxies.BankAccountsReport generateBankAccountsReport(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("BusinessBankModule.GenerateBankAccountsReport").withParams(params).execute(context);
		return result == null ? null : businessbankmodule.proxies.BankAccountsReport.initialize(context, result);
	}
	public static java.util.List<businessbankmodule.proxies.Account> getAllAccountsMicroflow(IContext context, businessbankmodule.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("BusinessBankModule.GetAllAccountsMicroflow").withParams(params).execute(context);
		java.util.List<businessbankmodule.proxies.Account> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(businessbankmodule.proxies.Account.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<businessbankmodule.proxies.PaymentOrder> getAllPaymentsForAccount(IContext context, businessbankmodule.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("BusinessBankModule.GetAllPaymentsForAccount").withParams(params).execute(context);
		java.util.List<businessbankmodule.proxies.PaymentOrder> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(businessbankmodule.proxies.PaymentOrder.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<businessbankmodule.proxies.PaymentOrder> getAllPaymentsForDocument(IContext context, businessbankmodule.proxies.DocumentAccountStatusReport _documentAccountStatusReport)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DocumentAccountStatusReport", _documentAccountStatusReport == null ? null : _documentAccountStatusReport.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("BusinessBankModule.GetAllPaymentsForDocument").withParams(params).execute(context);
		java.util.List<businessbankmodule.proxies.PaymentOrder> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(businessbankmodule.proxies.PaymentOrder.initialize(context, obj));
		}
		return result;
	}
	public static businessbankmodule.proxies.Bank getMyBank(IContext context, businessbankmodule.proxies.DocumentBankAccountsReport _documentBankAccountsReport)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DocumentBankAccountsReport", _documentBankAccountsReport == null ? null : _documentBankAccountsReport.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("BusinessBankModule.GetMyBank").withParams(params).execute(context);
		return result == null ? null : businessbankmodule.proxies.Bank.initialize(context, result);
	}
	public static void handleIncomingMT10x(IContext context, system.proxies.HttpRequest _httpRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		Core.microflowCall("BusinessBankModule.HandleIncomingMT10x").withParams(params).execute(context);
	}
	public static void handleMT9x0(IContext context, system.proxies.HttpRequest _httpRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		Core.microflowCall("BusinessBankModule.HandleMT9x0").withParams(params).execute(context);
	}
	public static void newPaymentOrderFromXML(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("BusinessBankModule.NewPaymentOrderFromXML").withParams(params).execute(context);
	}
	public static java.util.List<businessbankmodule.proxies.PaymentOrder> paymentOrdersByAccount(IContext context, businessbankmodule.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("BusinessBankModule.PaymentOrdersByAccount").withParams(params).execute(context);
		java.util.List<businessbankmodule.proxies.PaymentOrder> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(businessbankmodule.proxies.PaymentOrder.initialize(context, obj));
		}
		return result;
	}
	public static void pDFAccountStatusReport(IContext context, businessbankmodule.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("BusinessBankModule.PDFAccountStatusReport").withParams(params).execute(context);
	}
	public static void pDFBankAccountsReport(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("BusinessBankModule.PDFBankAccountsReport").withParams(params).execute(context);
	}
	public static void performOrder(IContext context, java.lang.String _accountNumber, boolean _creditor, businessbankmodule.proxies.PaymentOrder _paymentOrder)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("accountNumber", _accountNumber);
		params.put("creditor", _creditor);
		params.put("PaymentOrder", _paymentOrder == null ? null : _paymentOrder.getMendixObject());
		Core.microflowCall("BusinessBankModule.PerformOrder").withParams(params).execute(context);
	}
	public static void postBankBillingAccountStatusReport(IContext context, businessbankmodule.proxies.DocumentBankBillingAccountStatusReport _documentBankBillingAccountStatusReport)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DocumentBankBillingAccountStatusReport", _documentBankBillingAccountStatusReport == null ? null : _documentBankBillingAccountStatusReport.getMendixObject());
		Core.microflowCall("BusinessBankModule.PostBankBillingAccountStatusReport").withParams(params).execute(context);
	}
	public static boolean sanityCheck(IContext context, businessbankmodule.proxies.PaymentOrder _paymentOrder)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PaymentOrder", _paymentOrder == null ? null : _paymentOrder.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("BusinessBankModule.SanityCheck").withParams(params).execute(context);
	}
	public static void xMLAccountStatusReport(IContext context, businessbankmodule.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("BusinessBankModule.XMLAccountStatusReport").withParams(params).execute(context);
	}
	public static void xMLBankAccountsReport(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("BusinessBankModule.XMLBankAccountsReport").withParams(params).execute(context);
	}
}