// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package businessbankmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GenerateAccountNumber extends CustomJavaAction<java.lang.String>
{
	private java.lang.String bankCode;

	public GenerateAccountNumber(IContext context, java.lang.String bankCode)
	{
		super(context);
		this.bankCode = bankCode;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		Long sum = 0L;
		try {
			sum = Long.parseLong(this.bankCode);
		} catch (Exception e) {}
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < 13; i++) {
			int num = (int)(Math.random()*10);
			sum *=10;
			sum += num;
			sb.append(num);
		}
		double result = 98-sum * 100%97;
		return this.bankCode + "-" + sb.toString() + "-" + (int)result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateAccountNumber";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
