// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package businessbankmodule.proxies;

public class Account
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject accountMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BusinessBankModule.Account";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		number("number"),
		openingDate("openingDate"),
		active("active"),
		balance("balance"),
		closeDate("closeDate"),
		transferedToAccount("transferedToAccount"),
		accountClient("BusinessBankModule.accountClient"),
		accountBank("BusinessBankModule.accountBank");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Account(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BusinessBankModule.Account"));
	}

	protected Account(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject accountMendixObject)
	{
		if (accountMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BusinessBankModule.Account", accountMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BusinessBankModule.Account");

		this.accountMendixObject = accountMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Account.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static businessbankmodule.proxies.Account initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return businessbankmodule.proxies.Account.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static businessbankmodule.proxies.Account initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new businessbankmodule.proxies.Account(context, mendixObject);
	}

	public static businessbankmodule.proxies.Account load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return businessbankmodule.proxies.Account.initialize(context, mendixObject);
	}

	public static java.util.List<businessbankmodule.proxies.Account> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<businessbankmodule.proxies.Account> result = new java.util.ArrayList<businessbankmodule.proxies.Account>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//BusinessBankModule.Account" + xpathConstraint))
			result.add(businessbankmodule.proxies.Account.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of number
	 */
	public final java.lang.String getnumber()
	{
		return getnumber(getContext());
	}

	/**
	 * @param context
	 * @return value of number
	 */
	public final java.lang.String getnumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.number.toString());
	}

	/**
	 * Set value of number
	 * @param number
	 */
	public final void setnumber(java.lang.String number)
	{
		setnumber(getContext(), number);
	}

	/**
	 * Set value of number
	 * @param context
	 * @param number
	 */
	public final void setnumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String number)
	{
		getMendixObject().setValue(context, MemberNames.number.toString(), number);
	}

	/**
	 * @return value of openingDate
	 */
	public final java.util.Date getopeningDate()
	{
		return getopeningDate(getContext());
	}

	/**
	 * @param context
	 * @return value of openingDate
	 */
	public final java.util.Date getopeningDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.openingDate.toString());
	}

	/**
	 * Set value of openingDate
	 * @param openingdate
	 */
	public final void setopeningDate(java.util.Date openingdate)
	{
		setopeningDate(getContext(), openingdate);
	}

	/**
	 * Set value of openingDate
	 * @param context
	 * @param openingdate
	 */
	public final void setopeningDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date openingdate)
	{
		getMendixObject().setValue(context, MemberNames.openingDate.toString(), openingdate);
	}

	/**
	 * @return value of active
	 */
	public final java.lang.Boolean getactive()
	{
		return getactive(getContext());
	}

	/**
	 * @param context
	 * @return value of active
	 */
	public final java.lang.Boolean getactive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.active.toString());
	}

	/**
	 * Set value of active
	 * @param active
	 */
	public final void setactive(java.lang.Boolean active)
	{
		setactive(getContext(), active);
	}

	/**
	 * Set value of active
	 * @param context
	 * @param active
	 */
	public final void setactive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.active.toString(), active);
	}

	/**
	 * @return value of balance
	 */
	public final java.math.BigDecimal getbalance()
	{
		return getbalance(getContext());
	}

	/**
	 * @param context
	 * @return value of balance
	 */
	public final java.math.BigDecimal getbalance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.balance.toString());
	}

	/**
	 * Set value of balance
	 * @param balance
	 */
	public final void setbalance(java.math.BigDecimal balance)
	{
		setbalance(getContext(), balance);
	}

	/**
	 * Set value of balance
	 * @param context
	 * @param balance
	 */
	public final void setbalance(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal balance)
	{
		getMendixObject().setValue(context, MemberNames.balance.toString(), balance);
	}

	/**
	 * @return value of closeDate
	 */
	public final java.util.Date getcloseDate()
	{
		return getcloseDate(getContext());
	}

	/**
	 * @param context
	 * @return value of closeDate
	 */
	public final java.util.Date getcloseDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.closeDate.toString());
	}

	/**
	 * Set value of closeDate
	 * @param closedate
	 */
	public final void setcloseDate(java.util.Date closedate)
	{
		setcloseDate(getContext(), closedate);
	}

	/**
	 * Set value of closeDate
	 * @param context
	 * @param closedate
	 */
	public final void setcloseDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date closedate)
	{
		getMendixObject().setValue(context, MemberNames.closeDate.toString(), closedate);
	}

	/**
	 * @return value of transferedToAccount
	 */
	public final java.lang.String gettransferedToAccount()
	{
		return gettransferedToAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of transferedToAccount
	 */
	public final java.lang.String gettransferedToAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.transferedToAccount.toString());
	}

	/**
	 * Set value of transferedToAccount
	 * @param transferedtoaccount
	 */
	public final void settransferedToAccount(java.lang.String transferedtoaccount)
	{
		settransferedToAccount(getContext(), transferedtoaccount);
	}

	/**
	 * Set value of transferedToAccount
	 * @param context
	 * @param transferedtoaccount
	 */
	public final void settransferedToAccount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String transferedtoaccount)
	{
		getMendixObject().setValue(context, MemberNames.transferedToAccount.toString(), transferedtoaccount);
	}

	/**
	 * @return value of accountClient
	 */
	public final businessbankmodule.proxies.Client getaccountClient() throws com.mendix.core.CoreException
	{
		return getaccountClient(getContext());
	}

	/**
	 * @param context
	 * @return value of accountClient
	 */
	public final businessbankmodule.proxies.Client getaccountClient(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.Client result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.accountClient.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.Client.load(context, identifier);
		return result;
	}

	/**
	 * Set value of accountClient
	 * @param accountclient
	 */
	public final void setaccountClient(businessbankmodule.proxies.Client accountclient)
	{
		setaccountClient(getContext(), accountclient);
	}

	/**
	 * Set value of accountClient
	 * @param context
	 * @param accountclient
	 */
	public final void setaccountClient(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.Client accountclient)
	{
		if (accountclient == null)
			getMendixObject().setValue(context, MemberNames.accountClient.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.accountClient.toString(), accountclient.getMendixObject().getId());
	}

	/**
	 * @return value of accountBank
	 */
	public final businessbankmodule.proxies.Bank getaccountBank() throws com.mendix.core.CoreException
	{
		return getaccountBank(getContext());
	}

	/**
	 * @param context
	 * @return value of accountBank
	 */
	public final businessbankmodule.proxies.Bank getaccountBank(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.Bank result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.accountBank.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.Bank.load(context, identifier);
		return result;
	}

	/**
	 * Set value of accountBank
	 * @param accountbank
	 */
	public final void setaccountBank(businessbankmodule.proxies.Bank accountbank)
	{
		setaccountBank(getContext(), accountbank);
	}

	/**
	 * Set value of accountBank
	 * @param context
	 * @param accountbank
	 */
	public final void setaccountBank(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.Bank accountbank)
	{
		if (accountbank == null)
			getMendixObject().setValue(context, MemberNames.accountBank.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.accountBank.toString(), accountbank.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return accountMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final businessbankmodule.proxies.Account that = (businessbankmodule.proxies.Account) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BusinessBankModule.Account";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
