// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package businessbankmodule.proxies;

public class Bank
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bankMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BusinessBankModule.Bank";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		code("code"),
		name("name"),
		SWIFTcode("SWIFTcode"),
		billingAccount("billingAccount"),
		address("address"),
		phone("phone"),
		thisBank("thisBank"),
		bankCity("BusinessBankModule.bankCity"),
		BillingAccount_Bank("CentralBankModule.BillingAccount_Bank");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Bank(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BusinessBankModule.Bank"));
	}

	protected Bank(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bankMendixObject)
	{
		if (bankMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BusinessBankModule.Bank", bankMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BusinessBankModule.Bank");

		this.bankMendixObject = bankMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Bank.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static businessbankmodule.proxies.Bank initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return businessbankmodule.proxies.Bank.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static businessbankmodule.proxies.Bank initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new businessbankmodule.proxies.Bank(context, mendixObject);
	}

	public static businessbankmodule.proxies.Bank load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return businessbankmodule.proxies.Bank.initialize(context, mendixObject);
	}

	public static java.util.List<businessbankmodule.proxies.Bank> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<businessbankmodule.proxies.Bank> result = new java.util.ArrayList<businessbankmodule.proxies.Bank>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//BusinessBankModule.Bank" + xpathConstraint))
			result.add(businessbankmodule.proxies.Bank.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of code
	 */
	public final java.lang.String getcode()
	{
		return getcode(getContext());
	}

	/**
	 * @param context
	 * @return value of code
	 */
	public final java.lang.String getcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.code.toString());
	}

	/**
	 * Set value of code
	 * @param code
	 */
	public final void setcode(java.lang.String code)
	{
		setcode(getContext(), code);
	}

	/**
	 * Set value of code
	 * @param context
	 * @param code
	 */
	public final void setcode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String code)
	{
		getMendixObject().setValue(context, MemberNames.code.toString(), code);
	}

	/**
	 * @return value of name
	 */
	public final java.lang.String getname()
	{
		return getname(getContext());
	}

	/**
	 * @param context
	 * @return value of name
	 */
	public final java.lang.String getname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.name.toString());
	}

	/**
	 * Set value of name
	 * @param name
	 */
	public final void setname(java.lang.String name)
	{
		setname(getContext(), name);
	}

	/**
	 * Set value of name
	 * @param context
	 * @param name
	 */
	public final void setname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.name.toString(), name);
	}

	/**
	 * @return value of SWIFTcode
	 */
	public final java.lang.String getSWIFTcode()
	{
		return getSWIFTcode(getContext());
	}

	/**
	 * @param context
	 * @return value of SWIFTcode
	 */
	public final java.lang.String getSWIFTcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SWIFTcode.toString());
	}

	/**
	 * Set value of SWIFTcode
	 * @param swiftcode
	 */
	public final void setSWIFTcode(java.lang.String swiftcode)
	{
		setSWIFTcode(getContext(), swiftcode);
	}

	/**
	 * Set value of SWIFTcode
	 * @param context
	 * @param swiftcode
	 */
	public final void setSWIFTcode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String swiftcode)
	{
		getMendixObject().setValue(context, MemberNames.SWIFTcode.toString(), swiftcode);
	}

	/**
	 * @return value of billingAccount
	 */
	public final java.lang.String getbillingAccount()
	{
		return getbillingAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of billingAccount
	 */
	public final java.lang.String getbillingAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.billingAccount.toString());
	}

	/**
	 * Set value of billingAccount
	 * @param billingaccount
	 */
	public final void setbillingAccount(java.lang.String billingaccount)
	{
		setbillingAccount(getContext(), billingaccount);
	}

	/**
	 * Set value of billingAccount
	 * @param context
	 * @param billingaccount
	 */
	public final void setbillingAccount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String billingaccount)
	{
		getMendixObject().setValue(context, MemberNames.billingAccount.toString(), billingaccount);
	}

	/**
	 * @return value of address
	 */
	public final java.lang.String getaddress()
	{
		return getaddress(getContext());
	}

	/**
	 * @param context
	 * @return value of address
	 */
	public final java.lang.String getaddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.address.toString());
	}

	/**
	 * Set value of address
	 * @param address
	 */
	public final void setaddress(java.lang.String address)
	{
		setaddress(getContext(), address);
	}

	/**
	 * Set value of address
	 * @param context
	 * @param address
	 */
	public final void setaddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.address.toString(), address);
	}

	/**
	 * @return value of phone
	 */
	public final java.lang.String getphone()
	{
		return getphone(getContext());
	}

	/**
	 * @param context
	 * @return value of phone
	 */
	public final java.lang.String getphone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.phone.toString());
	}

	/**
	 * Set value of phone
	 * @param phone
	 */
	public final void setphone(java.lang.String phone)
	{
		setphone(getContext(), phone);
	}

	/**
	 * Set value of phone
	 * @param context
	 * @param phone
	 */
	public final void setphone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.phone.toString(), phone);
	}

	/**
	 * @return value of thisBank
	 */
	public final java.lang.Boolean getthisBank()
	{
		return getthisBank(getContext());
	}

	/**
	 * @param context
	 * @return value of thisBank
	 */
	public final java.lang.Boolean getthisBank(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.thisBank.toString());
	}

	/**
	 * Set value of thisBank
	 * @param thisbank
	 */
	public final void setthisBank(java.lang.Boolean thisbank)
	{
		setthisBank(getContext(), thisbank);
	}

	/**
	 * Set value of thisBank
	 * @param context
	 * @param thisbank
	 */
	public final void setthisBank(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean thisbank)
	{
		getMendixObject().setValue(context, MemberNames.thisBank.toString(), thisbank);
	}

	/**
	 * @return value of bankCity
	 */
	public final businessbankmodule.proxies.City getbankCity() throws com.mendix.core.CoreException
	{
		return getbankCity(getContext());
	}

	/**
	 * @param context
	 * @return value of bankCity
	 */
	public final businessbankmodule.proxies.City getbankCity(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.City result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.bankCity.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.City.load(context, identifier);
		return result;
	}

	/**
	 * Set value of bankCity
	 * @param bankcity
	 */
	public final void setbankCity(businessbankmodule.proxies.City bankcity)
	{
		setbankCity(getContext(), bankcity);
	}

	/**
	 * Set value of bankCity
	 * @param context
	 * @param bankcity
	 */
	public final void setbankCity(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.City bankcity)
	{
		if (bankcity == null)
			getMendixObject().setValue(context, MemberNames.bankCity.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.bankCity.toString(), bankcity.getMendixObject().getId());
	}

	/**
	 * @return value of BillingAccount_Bank
	 */
	public final centralbankmodule.proxies.BillingAccount getBillingAccount_Bank() throws com.mendix.core.CoreException
	{
		return getBillingAccount_Bank(getContext());
	}

	/**
	 * @param context
	 * @return value of BillingAccount_Bank
	 */
	public final centralbankmodule.proxies.BillingAccount getBillingAccount_Bank(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		centralbankmodule.proxies.BillingAccount result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BillingAccount_Bank.toString());
		if (identifier != null)
			result = centralbankmodule.proxies.BillingAccount.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BillingAccount_Bank
	 * @param billingaccount_bank
	 */
	public final void setBillingAccount_Bank(centralbankmodule.proxies.BillingAccount billingaccount_bank)
	{
		setBillingAccount_Bank(getContext(), billingaccount_bank);
	}

	/**
	 * Set value of BillingAccount_Bank
	 * @param context
	 * @param billingaccount_bank
	 */
	public final void setBillingAccount_Bank(com.mendix.systemwideinterfaces.core.IContext context, centralbankmodule.proxies.BillingAccount billingaccount_bank)
	{
		if (billingaccount_bank == null)
			getMendixObject().setValue(context, MemberNames.BillingAccount_Bank.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BillingAccount_Bank.toString(), billingaccount_bank.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bankMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final businessbankmodule.proxies.Bank that = (businessbankmodule.proxies.Bank) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BusinessBankModule.Bank";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
