// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package businessbankmodule.proxies;

public class TransferToAccountsPage_DataGrid extends system.proxies.Paging
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BusinessBankModule.TransferToAccountsPage_DataGrid";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		number("number"),
		openingDate("openingDate"),
		balance("balance"),
		closeDate("closeDate"),
		transferedToAccount("transferedToAccount"),
		PageNumber("PageNumber"),
		IsSortable("IsSortable"),
		SortAttribute("SortAttribute"),
		SortAscending("SortAscending"),
		HasMoreData("HasMoreData");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TransferToAccountsPage_DataGrid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BusinessBankModule.TransferToAccountsPage_DataGrid"));
	}

	protected TransferToAccountsPage_DataGrid(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transferToAccountsPage_DataGridMendixObject)
	{
		super(context, transferToAccountsPage_DataGridMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("BusinessBankModule.TransferToAccountsPage_DataGrid", transferToAccountsPage_DataGridMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BusinessBankModule.TransferToAccountsPage_DataGrid");
	}

	/**
	 * @deprecated Use 'TransferToAccountsPage_DataGrid.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static businessbankmodule.proxies.TransferToAccountsPage_DataGrid initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return businessbankmodule.proxies.TransferToAccountsPage_DataGrid.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static businessbankmodule.proxies.TransferToAccountsPage_DataGrid initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new businessbankmodule.proxies.TransferToAccountsPage_DataGrid(context, mendixObject);
	}

	public static businessbankmodule.proxies.TransferToAccountsPage_DataGrid load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return businessbankmodule.proxies.TransferToAccountsPage_DataGrid.initialize(context, mendixObject);
	}

	/**
	 * @return value of number
	 */
	public final java.lang.String getnumber()
	{
		return getnumber(getContext());
	}

	/**
	 * @param context
	 * @return value of number
	 */
	public final java.lang.String getnumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.number.toString());
	}

	/**
	 * Set value of number
	 * @param number
	 */
	public final void setnumber(java.lang.String number)
	{
		setnumber(getContext(), number);
	}

	/**
	 * Set value of number
	 * @param context
	 * @param number
	 */
	public final void setnumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String number)
	{
		getMendixObject().setValue(context, MemberNames.number.toString(), number);
	}

	/**
	 * @return value of openingDate
	 */
	public final java.util.Date getopeningDate()
	{
		return getopeningDate(getContext());
	}

	/**
	 * @param context
	 * @return value of openingDate
	 */
	public final java.util.Date getopeningDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.openingDate.toString());
	}

	/**
	 * Set value of openingDate
	 * @param openingdate
	 */
	public final void setopeningDate(java.util.Date openingdate)
	{
		setopeningDate(getContext(), openingdate);
	}

	/**
	 * Set value of openingDate
	 * @param context
	 * @param openingdate
	 */
	public final void setopeningDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date openingdate)
	{
		getMendixObject().setValue(context, MemberNames.openingDate.toString(), openingdate);
	}

	/**
	 * @return value of balance
	 */
	public final java.math.BigDecimal getbalance()
	{
		return getbalance(getContext());
	}

	/**
	 * @param context
	 * @return value of balance
	 */
	public final java.math.BigDecimal getbalance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.balance.toString());
	}

	/**
	 * Set value of balance
	 * @param balance
	 */
	public final void setbalance(java.math.BigDecimal balance)
	{
		setbalance(getContext(), balance);
	}

	/**
	 * Set value of balance
	 * @param context
	 * @param balance
	 */
	public final void setbalance(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal balance)
	{
		getMendixObject().setValue(context, MemberNames.balance.toString(), balance);
	}

	/**
	 * @return value of closeDate
	 */
	public final java.util.Date getcloseDate()
	{
		return getcloseDate(getContext());
	}

	/**
	 * @param context
	 * @return value of closeDate
	 */
	public final java.util.Date getcloseDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.closeDate.toString());
	}

	/**
	 * Set value of closeDate
	 * @param closedate
	 */
	public final void setcloseDate(java.util.Date closedate)
	{
		setcloseDate(getContext(), closedate);
	}

	/**
	 * Set value of closeDate
	 * @param context
	 * @param closedate
	 */
	public final void setcloseDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date closedate)
	{
		getMendixObject().setValue(context, MemberNames.closeDate.toString(), closedate);
	}

	/**
	 * @return value of transferedToAccount
	 */
	public final java.lang.String gettransferedToAccount()
	{
		return gettransferedToAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of transferedToAccount
	 */
	public final java.lang.String gettransferedToAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.transferedToAccount.toString());
	}

	/**
	 * Set value of transferedToAccount
	 * @param transferedtoaccount
	 */
	public final void settransferedToAccount(java.lang.String transferedtoaccount)
	{
		settransferedToAccount(getContext(), transferedtoaccount);
	}

	/**
	 * Set value of transferedToAccount
	 * @param context
	 * @param transferedtoaccount
	 */
	public final void settransferedToAccount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String transferedtoaccount)
	{
		getMendixObject().setValue(context, MemberNames.transferedToAccount.toString(), transferedtoaccount);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final businessbankmodule.proxies.TransferToAccountsPage_DataGrid that = (businessbankmodule.proxies.TransferToAccountsPage_DataGrid) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BusinessBankModule.TransferToAccountsPage_DataGrid";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
