// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package businessbankmodule.proxies;

public class TransferMessage
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject transferMessageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BusinessBankModule.TransferMessage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		messageCode("messageCode"),
		transferMessageType("transferMessageType"),
		amount("amount"),
		timestamp("timestamp"),
		handled("handled"),
		refererMessageCode("refererMessageCode"),
		SenderSwiftCode("SenderSwiftCode"),
		debtorBank("BusinessBankModule.debtorBank"),
		creditorBank("BusinessBankModule.creditorBank"),
		transferMessagePaymentOrder("BusinessBankModule.transferMessagePaymentOrder");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TransferMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BusinessBankModule.TransferMessage"));
	}

	protected TransferMessage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transferMessageMendixObject)
	{
		if (transferMessageMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BusinessBankModule.TransferMessage", transferMessageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BusinessBankModule.TransferMessage");

		this.transferMessageMendixObject = transferMessageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TransferMessage.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static businessbankmodule.proxies.TransferMessage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return businessbankmodule.proxies.TransferMessage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static businessbankmodule.proxies.TransferMessage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new businessbankmodule.proxies.TransferMessage(context, mendixObject);
	}

	public static businessbankmodule.proxies.TransferMessage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return businessbankmodule.proxies.TransferMessage.initialize(context, mendixObject);
	}

	public static java.util.List<businessbankmodule.proxies.TransferMessage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<businessbankmodule.proxies.TransferMessage> result = new java.util.ArrayList<businessbankmodule.proxies.TransferMessage>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//BusinessBankModule.TransferMessage" + xpathConstraint))
			result.add(businessbankmodule.proxies.TransferMessage.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of messageCode
	 */
	public final java.lang.String getmessageCode()
	{
		return getmessageCode(getContext());
	}

	/**
	 * @param context
	 * @return value of messageCode
	 */
	public final java.lang.String getmessageCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.messageCode.toString());
	}

	/**
	 * Set value of messageCode
	 * @param messagecode
	 */
	public final void setmessageCode(java.lang.String messagecode)
	{
		setmessageCode(getContext(), messagecode);
	}

	/**
	 * Set value of messageCode
	 * @param context
	 * @param messagecode
	 */
	public final void setmessageCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String messagecode)
	{
		getMendixObject().setValue(context, MemberNames.messageCode.toString(), messagecode);
	}

	/**
	 * Set value of transferMessageType
	 * @param transfermessagetype
	 */
	public final businessbankmodule.proxies.TransferMessageType gettransferMessageType()
	{
		return gettransferMessageType(getContext());
	}

	/**
	 * @param context
	 * @return value of transferMessageType
	 */
	public final businessbankmodule.proxies.TransferMessageType gettransferMessageType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.transferMessageType.toString());
		if (obj == null)
			return null;

		return businessbankmodule.proxies.TransferMessageType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of transferMessageType
	 * @param transfermessagetype
	 */
	public final void settransferMessageType(businessbankmodule.proxies.TransferMessageType transfermessagetype)
	{
		settransferMessageType(getContext(), transfermessagetype);
	}

	/**
	 * Set value of transferMessageType
	 * @param context
	 * @param transfermessagetype
	 */
	public final void settransferMessageType(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.TransferMessageType transfermessagetype)
	{
		if (transfermessagetype != null)
			getMendixObject().setValue(context, MemberNames.transferMessageType.toString(), transfermessagetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.transferMessageType.toString(), null);
	}

	/**
	 * @return value of amount
	 */
	public final java.math.BigDecimal getamount()
	{
		return getamount(getContext());
	}

	/**
	 * @param context
	 * @return value of amount
	 */
	public final java.math.BigDecimal getamount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.amount.toString());
	}

	/**
	 * Set value of amount
	 * @param amount
	 */
	public final void setamount(java.math.BigDecimal amount)
	{
		setamount(getContext(), amount);
	}

	/**
	 * Set value of amount
	 * @param context
	 * @param amount
	 */
	public final void setamount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amount)
	{
		getMendixObject().setValue(context, MemberNames.amount.toString(), amount);
	}

	/**
	 * @return value of timestamp
	 */
	public final java.util.Date gettimestamp()
	{
		return gettimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of timestamp
	 */
	public final java.util.Date gettimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.timestamp.toString());
	}

	/**
	 * Set value of timestamp
	 * @param timestamp
	 */
	public final void settimestamp(java.util.Date timestamp)
	{
		settimestamp(getContext(), timestamp);
	}

	/**
	 * Set value of timestamp
	 * @param context
	 * @param timestamp
	 */
	public final void settimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timestamp)
	{
		getMendixObject().setValue(context, MemberNames.timestamp.toString(), timestamp);
	}

	/**
	 * @return value of handled
	 */
	public final java.lang.Boolean gethandled()
	{
		return gethandled(getContext());
	}

	/**
	 * @param context
	 * @return value of handled
	 */
	public final java.lang.Boolean gethandled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.handled.toString());
	}

	/**
	 * Set value of handled
	 * @param handled
	 */
	public final void sethandled(java.lang.Boolean handled)
	{
		sethandled(getContext(), handled);
	}

	/**
	 * Set value of handled
	 * @param context
	 * @param handled
	 */
	public final void sethandled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean handled)
	{
		getMendixObject().setValue(context, MemberNames.handled.toString(), handled);
	}

	/**
	 * @return value of refererMessageCode
	 */
	public final java.lang.String getrefererMessageCode()
	{
		return getrefererMessageCode(getContext());
	}

	/**
	 * @param context
	 * @return value of refererMessageCode
	 */
	public final java.lang.String getrefererMessageCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.refererMessageCode.toString());
	}

	/**
	 * Set value of refererMessageCode
	 * @param referermessagecode
	 */
	public final void setrefererMessageCode(java.lang.String referermessagecode)
	{
		setrefererMessageCode(getContext(), referermessagecode);
	}

	/**
	 * Set value of refererMessageCode
	 * @param context
	 * @param referermessagecode
	 */
	public final void setrefererMessageCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String referermessagecode)
	{
		getMendixObject().setValue(context, MemberNames.refererMessageCode.toString(), referermessagecode);
	}

	/**
	 * @return value of SenderSwiftCode
	 */
	public final java.lang.String getSenderSwiftCode()
	{
		return getSenderSwiftCode(getContext());
	}

	/**
	 * @param context
	 * @return value of SenderSwiftCode
	 */
	public final java.lang.String getSenderSwiftCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SenderSwiftCode.toString());
	}

	/**
	 * Set value of SenderSwiftCode
	 * @param senderswiftcode
	 */
	public final void setSenderSwiftCode(java.lang.String senderswiftcode)
	{
		setSenderSwiftCode(getContext(), senderswiftcode);
	}

	/**
	 * Set value of SenderSwiftCode
	 * @param context
	 * @param senderswiftcode
	 */
	public final void setSenderSwiftCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String senderswiftcode)
	{
		getMendixObject().setValue(context, MemberNames.SenderSwiftCode.toString(), senderswiftcode);
	}

	/**
	 * @return value of debtorBank
	 */
	public final businessbankmodule.proxies.Bank getdebtorBank() throws com.mendix.core.CoreException
	{
		return getdebtorBank(getContext());
	}

	/**
	 * @param context
	 * @return value of debtorBank
	 */
	public final businessbankmodule.proxies.Bank getdebtorBank(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.Bank result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.debtorBank.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.Bank.load(context, identifier);
		return result;
	}

	/**
	 * Set value of debtorBank
	 * @param debtorbank
	 */
	public final void setdebtorBank(businessbankmodule.proxies.Bank debtorbank)
	{
		setdebtorBank(getContext(), debtorbank);
	}

	/**
	 * Set value of debtorBank
	 * @param context
	 * @param debtorbank
	 */
	public final void setdebtorBank(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.Bank debtorbank)
	{
		if (debtorbank == null)
			getMendixObject().setValue(context, MemberNames.debtorBank.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.debtorBank.toString(), debtorbank.getMendixObject().getId());
	}

	/**
	 * @return value of creditorBank
	 */
	public final businessbankmodule.proxies.Bank getcreditorBank() throws com.mendix.core.CoreException
	{
		return getcreditorBank(getContext());
	}

	/**
	 * @param context
	 * @return value of creditorBank
	 */
	public final businessbankmodule.proxies.Bank getcreditorBank(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businessbankmodule.proxies.Bank result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.creditorBank.toString());
		if (identifier != null)
			result = businessbankmodule.proxies.Bank.load(context, identifier);
		return result;
	}

	/**
	 * Set value of creditorBank
	 * @param creditorbank
	 */
	public final void setcreditorBank(businessbankmodule.proxies.Bank creditorbank)
	{
		setcreditorBank(getContext(), creditorbank);
	}

	/**
	 * Set value of creditorBank
	 * @param context
	 * @param creditorbank
	 */
	public final void setcreditorBank(com.mendix.systemwideinterfaces.core.IContext context, businessbankmodule.proxies.Bank creditorbank)
	{
		if (creditorbank == null)
			getMendixObject().setValue(context, MemberNames.creditorBank.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.creditorBank.toString(), creditorbank.getMendixObject().getId());
	}

	/**
	 * @return value of transferMessagePaymentOrder
	 */
	public final java.util.List<businessbankmodule.proxies.PaymentOrder> gettransferMessagePaymentOrder() throws com.mendix.core.CoreException
	{
		return gettransferMessagePaymentOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of transferMessagePaymentOrder
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<businessbankmodule.proxies.PaymentOrder> gettransferMessagePaymentOrder(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<businessbankmodule.proxies.PaymentOrder> result = new java.util.ArrayList<businessbankmodule.proxies.PaymentOrder>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.transferMessagePaymentOrder.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(businessbankmodule.proxies.PaymentOrder.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of transferMessagePaymentOrder
	 * @param transfermessagepaymentorder
	 */
	public final void settransferMessagePaymentOrder(java.util.List<businessbankmodule.proxies.PaymentOrder> transfermessagepaymentorder)
	{
		settransferMessagePaymentOrder(getContext(), transfermessagepaymentorder);
	}

	/**
	 * Set value of transferMessagePaymentOrder
	 * @param context
	 * @param transfermessagepaymentorder
	 */
	public final void settransferMessagePaymentOrder(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<businessbankmodule.proxies.PaymentOrder> transfermessagepaymentorder)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (businessbankmodule.proxies.PaymentOrder proxyObject : transfermessagepaymentorder)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.transferMessagePaymentOrder.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return transferMessageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final businessbankmodule.proxies.TransferMessage that = (businessbankmodule.proxies.TransferMessage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BusinessBankModule.TransferMessage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
